/* tslint:disable */
/* eslint-disable */
/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthenticationCreateRequestToken200Response
 */
export interface AuthenticationCreateRequestToken200Response {
    /**
     * 
     * @type {any}
     * @memberof AuthenticationCreateRequestToken200Response
     */
    success?: any | null;
    /**
     * 
     * @type {any}
     * @memberof AuthenticationCreateRequestToken200Response
     */
    expiresAt?: any | null;
    /**
     * 
     * @type {any}
     * @memberof AuthenticationCreateRequestToken200Response
     */
    requestToken?: any | null;
}

/**
 * Check if a given object implements the AuthenticationCreateRequestToken200Response interface.
 */
export function instanceOfAuthenticationCreateRequestToken200Response(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function AuthenticationCreateRequestToken200ResponseFromJSON(json: any): AuthenticationCreateRequestToken200Response {
    return AuthenticationCreateRequestToken200ResponseFromJSONTyped(json, false);
}

export function AuthenticationCreateRequestToken200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthenticationCreateRequestToken200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'success': !exists(json, 'success') ? undefined : json['success'],
        'expiresAt': !exists(json, 'expires_at') ? undefined : json['expires_at'],
        'requestToken': !exists(json, 'request_token') ? undefined : json['request_token'],
    };
}

export function AuthenticationCreateRequestToken200ResponseToJSON(value?: AuthenticationCreateRequestToken200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'success': value.success,
        'expires_at': value.expiresAt,
        'request_token': value.requestToken,
    };
}

