/* tslint:disable */
/* eslint-disable */
/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthenticationCreateSessionFromV4Token200Response
 */
export interface AuthenticationCreateSessionFromV4Token200Response {
    /**
     * 
     * @type {any}
     * @memberof AuthenticationCreateSessionFromV4Token200Response
     */
    success?: any | null;
    /**
     * 
     * @type {any}
     * @memberof AuthenticationCreateSessionFromV4Token200Response
     */
    sessionId?: any | null;
}

/**
 * Check if a given object implements the AuthenticationCreateSessionFromV4Token200Response interface.
 */
export function instanceOfAuthenticationCreateSessionFromV4Token200Response(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function AuthenticationCreateSessionFromV4Token200ResponseFromJSON(json: any): AuthenticationCreateSessionFromV4Token200Response {
    return AuthenticationCreateSessionFromV4Token200ResponseFromJSONTyped(json, false);
}

export function AuthenticationCreateSessionFromV4Token200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthenticationCreateSessionFromV4Token200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'success': !exists(json, 'success') ? undefined : json['success'],
        'sessionId': !exists(json, 'session_id') ? undefined : json['session_id'],
    };
}

export function AuthenticationCreateSessionFromV4Token200ResponseToJSON(value?: AuthenticationCreateSessionFromV4Token200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'success': value.success,
        'session_id': value.sessionId,
    };
}

