/* tslint:disable */
/* eslint-disable */
/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthenticationCreateGuestSession200Response
 */
export interface AuthenticationCreateGuestSession200Response {
    /**
     * 
     * @type {any}
     * @memberof AuthenticationCreateGuestSession200Response
     */
    success?: any | null;
    /**
     * 
     * @type {any}
     * @memberof AuthenticationCreateGuestSession200Response
     */
    guestSessionId?: any | null;
    /**
     * 
     * @type {any}
     * @memberof AuthenticationCreateGuestSession200Response
     */
    expiresAt?: any | null;
}

/**
 * Check if a given object implements the AuthenticationCreateGuestSession200Response interface.
 */
export function instanceOfAuthenticationCreateGuestSession200Response(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function AuthenticationCreateGuestSession200ResponseFromJSON(json: any): AuthenticationCreateGuestSession200Response {
    return AuthenticationCreateGuestSession200ResponseFromJSONTyped(json, false);
}

export function AuthenticationCreateGuestSession200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthenticationCreateGuestSession200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'success': !exists(json, 'success') ? undefined : json['success'],
        'guestSessionId': !exists(json, 'guest_session_id') ? undefined : json['guest_session_id'],
        'expiresAt': !exists(json, 'expires_at') ? undefined : json['expires_at'],
    };
}

export function AuthenticationCreateGuestSession200ResponseToJSON(value?: AuthenticationCreateGuestSession200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'success': value.success,
        'guest_session_id': value.guestSessionId,
        'expires_at': value.expiresAt,
    };
}

