/* tslint:disable */
/* eslint-disable */
/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CertificationMovieList200ResponseCertifications
 */
export interface CertificationMovieList200ResponseCertifications {
    /**
     * 
     * @type {any}
     * @memberof CertificationMovieList200ResponseCertifications
     */
    aU?: any | null;
    /**
     * 
     * @type {any}
     * @memberof CertificationMovieList200ResponseCertifications
     */
    bG?: any | null;
    /**
     * 
     * @type {any}
     * @memberof CertificationMovieList200ResponseCertifications
     */
    bR?: any | null;
    /**
     * 
     * @type {any}
     * @memberof CertificationMovieList200ResponseCertifications
     */
    cA?: any | null;
    /**
     * 
     * @type {any}
     * @memberof CertificationMovieList200ResponseCertifications
     */
    cAQC?: any | null;
    /**
     * 
     * @type {any}
     * @memberof CertificationMovieList200ResponseCertifications
     */
    dE?: any | null;
    /**
     * 
     * @type {any}
     * @memberof CertificationMovieList200ResponseCertifications
     */
    dK?: any | null;
    /**
     * 
     * @type {any}
     * @memberof CertificationMovieList200ResponseCertifications
     */
    eS?: any | null;
    /**
     * 
     * @type {any}
     * @memberof CertificationMovieList200ResponseCertifications
     */
    fI?: any | null;
    /**
     * 
     * @type {any}
     * @memberof CertificationMovieList200ResponseCertifications
     */
    fR?: any | null;
    /**
     * 
     * @type {any}
     * @memberof CertificationMovieList200ResponseCertifications
     */
    gB?: any | null;
    /**
     * 
     * @type {any}
     * @memberof CertificationMovieList200ResponseCertifications
     */
    hU?: any | null;
    /**
     * 
     * @type {any}
     * @memberof CertificationMovieList200ResponseCertifications
     */
    iN?: any | null;
    /**
     * 
     * @type {any}
     * @memberof CertificationMovieList200ResponseCertifications
     */
    iT?: any | null;
    /**
     * 
     * @type {any}
     * @memberof CertificationMovieList200ResponseCertifications
     */
    lT?: any | null;
    /**
     * 
     * @type {any}
     * @memberof CertificationMovieList200ResponseCertifications
     */
    mY?: any | null;
    /**
     * 
     * @type {any}
     * @memberof CertificationMovieList200ResponseCertifications
     */
    nL?: any | null;
    /**
     * 
     * @type {any}
     * @memberof CertificationMovieList200ResponseCertifications
     */
    nO?: any | null;
    /**
     * 
     * @type {any}
     * @memberof CertificationMovieList200ResponseCertifications
     */
    nZ?: any | null;
    /**
     * 
     * @type {any}
     * @memberof CertificationMovieList200ResponseCertifications
     */
    pH?: any | null;
    /**
     * 
     * @type {any}
     * @memberof CertificationMovieList200ResponseCertifications
     */
    pT?: any | null;
    /**
     * 
     * @type {any}
     * @memberof CertificationMovieList200ResponseCertifications
     */
    rU?: any | null;
    /**
     * 
     * @type {any}
     * @memberof CertificationMovieList200ResponseCertifications
     */
    sE?: any | null;
    /**
     * 
     * @type {any}
     * @memberof CertificationMovieList200ResponseCertifications
     */
    uS?: any | null;
    /**
     * 
     * @type {any}
     * @memberof CertificationMovieList200ResponseCertifications
     */
    kR?: any | null;
    /**
     * 
     * @type {any}
     * @memberof CertificationMovieList200ResponseCertifications
     */
    sK?: any | null;
    /**
     * 
     * @type {any}
     * @memberof CertificationMovieList200ResponseCertifications
     */
    tH?: any | null;
    /**
     * 
     * @type {any}
     * @memberof CertificationMovieList200ResponseCertifications
     */
    mX?: any | null;
    /**
     * 
     * @type {any}
     * @memberof CertificationMovieList200ResponseCertifications
     */
    iD?: any | null;
    /**
     * 
     * @type {any}
     * @memberof CertificationMovieList200ResponseCertifications
     */
    tR?: any | null;
    /**
     * 
     * @type {any}
     * @memberof CertificationMovieList200ResponseCertifications
     */
    aR?: any | null;
    /**
     * 
     * @type {any}
     * @memberof CertificationMovieList200ResponseCertifications
     */
    gR?: any | null;
    /**
     * 
     * @type {any}
     * @memberof CertificationMovieList200ResponseCertifications
     */
    tW?: any | null;
    /**
     * 
     * @type {any}
     * @memberof CertificationMovieList200ResponseCertifications
     */
    zA?: any | null;
    /**
     * 
     * @type {any}
     * @memberof CertificationMovieList200ResponseCertifications
     */
    sG?: any | null;
    /**
     * 
     * @type {any}
     * @memberof CertificationMovieList200ResponseCertifications
     */
    iE?: any | null;
    /**
     * 
     * @type {any}
     * @memberof CertificationMovieList200ResponseCertifications
     */
    pR?: any | null;
    /**
     * 
     * @type {any}
     * @memberof CertificationMovieList200ResponseCertifications
     */
    jP?: any | null;
    /**
     * 
     * @type {any}
     * @memberof CertificationMovieList200ResponseCertifications
     */
    vI?: any | null;
    /**
     * 
     * @type {any}
     * @memberof CertificationMovieList200ResponseCertifications
     */
    cH?: any | null;
    /**
     * 
     * @type {any}
     * @memberof CertificationMovieList200ResponseCertifications
     */
    iL?: any | null;
    /**
     * 
     * @type {any}
     * @memberof CertificationMovieList200ResponseCertifications
     */
    hK?: any | null;
    /**
     * 
     * @type {any}
     * @memberof CertificationMovieList200ResponseCertifications
     */
    mO?: any | null;
    /**
     * 
     * @type {any}
     * @memberof CertificationMovieList200ResponseCertifications
     */
    lV?: any | null;
    /**
     * 
     * @type {any}
     * @memberof CertificationMovieList200ResponseCertifications
     */
    lU?: any | null;
}

/**
 * Check if a given object implements the CertificationMovieList200ResponseCertifications interface.
 */
export function instanceOfCertificationMovieList200ResponseCertifications(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CertificationMovieList200ResponseCertificationsFromJSON(json: any): CertificationMovieList200ResponseCertifications {
    return CertificationMovieList200ResponseCertificationsFromJSONTyped(json, false);
}

export function CertificationMovieList200ResponseCertificationsFromJSONTyped(json: any, ignoreDiscriminator: boolean): CertificationMovieList200ResponseCertifications {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'aU': !exists(json, 'AU') ? undefined : json['AU'],
        'bG': !exists(json, 'BG') ? undefined : json['BG'],
        'bR': !exists(json, 'BR') ? undefined : json['BR'],
        'cA': !exists(json, 'CA') ? undefined : json['CA'],
        'cAQC': !exists(json, 'CA-QC') ? undefined : json['CA-QC'],
        'dE': !exists(json, 'DE') ? undefined : json['DE'],
        'dK': !exists(json, 'DK') ? undefined : json['DK'],
        'eS': !exists(json, 'ES') ? undefined : json['ES'],
        'fI': !exists(json, 'FI') ? undefined : json['FI'],
        'fR': !exists(json, 'FR') ? undefined : json['FR'],
        'gB': !exists(json, 'GB') ? undefined : json['GB'],
        'hU': !exists(json, 'HU') ? undefined : json['HU'],
        'iN': !exists(json, 'IN') ? undefined : json['IN'],
        'iT': !exists(json, 'IT') ? undefined : json['IT'],
        'lT': !exists(json, 'LT') ? undefined : json['LT'],
        'mY': !exists(json, 'MY') ? undefined : json['MY'],
        'nL': !exists(json, 'NL') ? undefined : json['NL'],
        'nO': !exists(json, 'NO') ? undefined : json['NO'],
        'nZ': !exists(json, 'NZ') ? undefined : json['NZ'],
        'pH': !exists(json, 'PH') ? undefined : json['PH'],
        'pT': !exists(json, 'PT') ? undefined : json['PT'],
        'rU': !exists(json, 'RU') ? undefined : json['RU'],
        'sE': !exists(json, 'SE') ? undefined : json['SE'],
        'uS': !exists(json, 'US') ? undefined : json['US'],
        'kR': !exists(json, 'KR') ? undefined : json['KR'],
        'sK': !exists(json, 'SK') ? undefined : json['SK'],
        'tH': !exists(json, 'TH') ? undefined : json['TH'],
        'mX': !exists(json, 'MX') ? undefined : json['MX'],
        'iD': !exists(json, 'ID') ? undefined : json['ID'],
        'tR': !exists(json, 'TR') ? undefined : json['TR'],
        'aR': !exists(json, 'AR') ? undefined : json['AR'],
        'gR': !exists(json, 'GR') ? undefined : json['GR'],
        'tW': !exists(json, 'TW') ? undefined : json['TW'],
        'zA': !exists(json, 'ZA') ? undefined : json['ZA'],
        'sG': !exists(json, 'SG') ? undefined : json['SG'],
        'iE': !exists(json, 'IE') ? undefined : json['IE'],
        'pR': !exists(json, 'PR') ? undefined : json['PR'],
        'jP': !exists(json, 'JP') ? undefined : json['JP'],
        'vI': !exists(json, 'VI') ? undefined : json['VI'],
        'cH': !exists(json, 'CH') ? undefined : json['CH'],
        'iL': !exists(json, 'IL') ? undefined : json['IL'],
        'hK': !exists(json, 'HK') ? undefined : json['HK'],
        'mO': !exists(json, 'MO') ? undefined : json['MO'],
        'lV': !exists(json, 'LV') ? undefined : json['LV'],
        'lU': !exists(json, 'LU') ? undefined : json['LU'],
    };
}

export function CertificationMovieList200ResponseCertificationsToJSON(value?: CertificationMovieList200ResponseCertifications | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'AU': value.aU,
        'BG': value.bG,
        'BR': value.bR,
        'CA': value.cA,
        'CA-QC': value.cAQC,
        'DE': value.dE,
        'DK': value.dK,
        'ES': value.eS,
        'FI': value.fI,
        'FR': value.fR,
        'GB': value.gB,
        'HU': value.hU,
        'IN': value.iN,
        'IT': value.iT,
        'LT': value.lT,
        'MY': value.mY,
        'NL': value.nL,
        'NO': value.nO,
        'NZ': value.nZ,
        'PH': value.pH,
        'PT': value.pT,
        'RU': value.rU,
        'SE': value.sE,
        'US': value.uS,
        'KR': value.kR,
        'SK': value.sK,
        'TH': value.tH,
        'MX': value.mX,
        'ID': value.iD,
        'TR': value.tR,
        'AR': value.aR,
        'GR': value.gR,
        'TW': value.tW,
        'ZA': value.zA,
        'SG': value.sG,
        'IE': value.iE,
        'PR': value.pR,
        'JP': value.jP,
        'VI': value.vI,
        'CH': value.cH,
        'IL': value.iL,
        'HK': value.hK,
        'MO': value.mO,
        'LV': value.lV,
        'LU': value.lU,
    };
}

