/* tslint:disable */
/* eslint-disable */
/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CertificationsTvList200ResponseCertifications
 */
export interface CertificationsTvList200ResponseCertifications {
    /**
     * 
     * @type {any}
     * @memberof CertificationsTvList200ResponseCertifications
     */
    aU?: any | null;
    /**
     * 
     * @type {any}
     * @memberof CertificationsTvList200ResponseCertifications
     */
    bR?: any | null;
    /**
     * 
     * @type {any}
     * @memberof CertificationsTvList200ResponseCertifications
     */
    cA?: any | null;
    /**
     * 
     * @type {any}
     * @memberof CertificationsTvList200ResponseCertifications
     */
    cAQC?: any | null;
    /**
     * 
     * @type {any}
     * @memberof CertificationsTvList200ResponseCertifications
     */
    dE?: any | null;
    /**
     * 
     * @type {any}
     * @memberof CertificationsTvList200ResponseCertifications
     */
    eS?: any | null;
    /**
     * 
     * @type {any}
     * @memberof CertificationsTvList200ResponseCertifications
     */
    fR?: any | null;
    /**
     * 
     * @type {any}
     * @memberof CertificationsTvList200ResponseCertifications
     */
    gB?: any | null;
    /**
     * 
     * @type {any}
     * @memberof CertificationsTvList200ResponseCertifications
     */
    hU?: any | null;
    /**
     * 
     * @type {any}
     * @memberof CertificationsTvList200ResponseCertifications
     */
    kR?: any | null;
    /**
     * 
     * @type {any}
     * @memberof CertificationsTvList200ResponseCertifications
     */
    lT?: any | null;
    /**
     * 
     * @type {any}
     * @memberof CertificationsTvList200ResponseCertifications
     */
    nL?: any | null;
    /**
     * 
     * @type {any}
     * @memberof CertificationsTvList200ResponseCertifications
     */
    pH?: any | null;
    /**
     * 
     * @type {any}
     * @memberof CertificationsTvList200ResponseCertifications
     */
    pT?: any | null;
    /**
     * 
     * @type {any}
     * @memberof CertificationsTvList200ResponseCertifications
     */
    rU?: any | null;
    /**
     * 
     * @type {any}
     * @memberof CertificationsTvList200ResponseCertifications
     */
    sK?: any | null;
    /**
     * 
     * @type {any}
     * @memberof CertificationsTvList200ResponseCertifications
     */
    tH?: any | null;
    /**
     * 
     * @type {any}
     * @memberof CertificationsTvList200ResponseCertifications
     */
    uS?: any | null;
    /**
     * 
     * @type {any}
     * @memberof CertificationsTvList200ResponseCertifications
     */
    iT?: any | null;
    /**
     * 
     * @type {any}
     * @memberof CertificationsTvList200ResponseCertifications
     */
    fI?: any | null;
    /**
     * 
     * @type {any}
     * @memberof CertificationsTvList200ResponseCertifications
     */
    mY?: any | null;
    /**
     * 
     * @type {any}
     * @memberof CertificationsTvList200ResponseCertifications
     */
    nZ?: any | null;
    /**
     * 
     * @type {any}
     * @memberof CertificationsTvList200ResponseCertifications
     */
    nO?: any | null;
    /**
     * 
     * @type {any}
     * @memberof CertificationsTvList200ResponseCertifications
     */
    bG?: any | null;
    /**
     * 
     * @type {any}
     * @memberof CertificationsTvList200ResponseCertifications
     */
    mX?: any | null;
    /**
     * 
     * @type {any}
     * @memberof CertificationsTvList200ResponseCertifications
     */
    iN?: any | null;
    /**
     * 
     * @type {any}
     * @memberof CertificationsTvList200ResponseCertifications
     */
    dK?: any | null;
    /**
     * 
     * @type {any}
     * @memberof CertificationsTvList200ResponseCertifications
     */
    sE?: any | null;
    /**
     * 
     * @type {any}
     * @memberof CertificationsTvList200ResponseCertifications
     */
    iD?: any | null;
    /**
     * 
     * @type {any}
     * @memberof CertificationsTvList200ResponseCertifications
     */
    tR?: any | null;
    /**
     * 
     * @type {any}
     * @memberof CertificationsTvList200ResponseCertifications
     */
    aR?: any | null;
    /**
     * 
     * @type {any}
     * @memberof CertificationsTvList200ResponseCertifications
     */
    pL?: any | null;
    /**
     * 
     * @type {any}
     * @memberof CertificationsTvList200ResponseCertifications
     */
    mA?: any | null;
    /**
     * 
     * @type {any}
     * @memberof CertificationsTvList200ResponseCertifications
     */
    gR?: any | null;
    /**
     * 
     * @type {any}
     * @memberof CertificationsTvList200ResponseCertifications
     */
    iL?: any | null;
    /**
     * 
     * @type {any}
     * @memberof CertificationsTvList200ResponseCertifications
     */
    tW?: any | null;
    /**
     * 
     * @type {any}
     * @memberof CertificationsTvList200ResponseCertifications
     */
    zA?: any | null;
    /**
     * 
     * @type {any}
     * @memberof CertificationsTvList200ResponseCertifications
     */
    sG?: any | null;
    /**
     * 
     * @type {any}
     * @memberof CertificationsTvList200ResponseCertifications
     */
    pR?: any | null;
    /**
     * 
     * @type {any}
     * @memberof CertificationsTvList200ResponseCertifications
     */
    vI?: any | null;
}

/**
 * Check if a given object implements the CertificationsTvList200ResponseCertifications interface.
 */
export function instanceOfCertificationsTvList200ResponseCertifications(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CertificationsTvList200ResponseCertificationsFromJSON(json: any): CertificationsTvList200ResponseCertifications {
    return CertificationsTvList200ResponseCertificationsFromJSONTyped(json, false);
}

export function CertificationsTvList200ResponseCertificationsFromJSONTyped(json: any, ignoreDiscriminator: boolean): CertificationsTvList200ResponseCertifications {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'aU': !exists(json, 'AU') ? undefined : json['AU'],
        'bR': !exists(json, 'BR') ? undefined : json['BR'],
        'cA': !exists(json, 'CA') ? undefined : json['CA'],
        'cAQC': !exists(json, 'CA-QC') ? undefined : json['CA-QC'],
        'dE': !exists(json, 'DE') ? undefined : json['DE'],
        'eS': !exists(json, 'ES') ? undefined : json['ES'],
        'fR': !exists(json, 'FR') ? undefined : json['FR'],
        'gB': !exists(json, 'GB') ? undefined : json['GB'],
        'hU': !exists(json, 'HU') ? undefined : json['HU'],
        'kR': !exists(json, 'KR') ? undefined : json['KR'],
        'lT': !exists(json, 'LT') ? undefined : json['LT'],
        'nL': !exists(json, 'NL') ? undefined : json['NL'],
        'pH': !exists(json, 'PH') ? undefined : json['PH'],
        'pT': !exists(json, 'PT') ? undefined : json['PT'],
        'rU': !exists(json, 'RU') ? undefined : json['RU'],
        'sK': !exists(json, 'SK') ? undefined : json['SK'],
        'tH': !exists(json, 'TH') ? undefined : json['TH'],
        'uS': !exists(json, 'US') ? undefined : json['US'],
        'iT': !exists(json, 'IT') ? undefined : json['IT'],
        'fI': !exists(json, 'FI') ? undefined : json['FI'],
        'mY': !exists(json, 'MY') ? undefined : json['MY'],
        'nZ': !exists(json, 'NZ') ? undefined : json['NZ'],
        'nO': !exists(json, 'NO') ? undefined : json['NO'],
        'bG': !exists(json, 'BG') ? undefined : json['BG'],
        'mX': !exists(json, 'MX') ? undefined : json['MX'],
        'iN': !exists(json, 'IN') ? undefined : json['IN'],
        'dK': !exists(json, 'DK') ? undefined : json['DK'],
        'sE': !exists(json, 'SE') ? undefined : json['SE'],
        'iD': !exists(json, 'ID') ? undefined : json['ID'],
        'tR': !exists(json, 'TR') ? undefined : json['TR'],
        'aR': !exists(json, 'AR') ? undefined : json['AR'],
        'pL': !exists(json, 'PL') ? undefined : json['PL'],
        'mA': !exists(json, 'MA') ? undefined : json['MA'],
        'gR': !exists(json, 'GR') ? undefined : json['GR'],
        'iL': !exists(json, 'IL') ? undefined : json['IL'],
        'tW': !exists(json, 'TW') ? undefined : json['TW'],
        'zA': !exists(json, 'ZA') ? undefined : json['ZA'],
        'sG': !exists(json, 'SG') ? undefined : json['SG'],
        'pR': !exists(json, 'PR') ? undefined : json['PR'],
        'vI': !exists(json, 'VI') ? undefined : json['VI'],
    };
}

export function CertificationsTvList200ResponseCertificationsToJSON(value?: CertificationsTvList200ResponseCertifications | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'AU': value.aU,
        'BR': value.bR,
        'CA': value.cA,
        'CA-QC': value.cAQC,
        'DE': value.dE,
        'ES': value.eS,
        'FR': value.fR,
        'GB': value.gB,
        'HU': value.hU,
        'KR': value.kR,
        'LT': value.lT,
        'NL': value.nL,
        'PH': value.pH,
        'PT': value.pT,
        'RU': value.rU,
        'SK': value.sK,
        'TH': value.tH,
        'US': value.uS,
        'IT': value.iT,
        'FI': value.fI,
        'MY': value.mY,
        'NZ': value.nZ,
        'NO': value.nO,
        'BG': value.bG,
        'MX': value.mX,
        'IN': value.iN,
        'DK': value.dK,
        'SE': value.sE,
        'ID': value.iD,
        'TR': value.tR,
        'AR': value.aR,
        'PL': value.pL,
        'MA': value.mA,
        'GR': value.gR,
        'IL': value.iL,
        'TW': value.tW,
        'ZA': value.zA,
        'SG': value.sG,
        'PR': value.pR,
        'VI': value.vI,
    };
}

