/* tslint:disable */
/* eslint-disable */
/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CompanyImages200Response
 */
export interface CompanyImages200Response {
    /**
     * 
     * @type {any}
     * @memberof CompanyImages200Response
     */
    id?: any | null;
    /**
     * 
     * @type {any}
     * @memberof CompanyImages200Response
     */
    logos?: any | null;
}

/**
 * Check if a given object implements the CompanyImages200Response interface.
 */
export function instanceOfCompanyImages200Response(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CompanyImages200ResponseFromJSON(json: any): CompanyImages200Response {
    return CompanyImages200ResponseFromJSONTyped(json, false);
}

export function CompanyImages200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CompanyImages200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'logos': !exists(json, 'logos') ? undefined : json['logos'],
    };
}

export function CompanyImages200ResponseToJSON(value?: CompanyImages200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'logos': value.logos,
    };
}

