/* tslint:disable */
/* eslint-disable */
/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GenreMovieList200Response
 */
export interface GenreMovieList200Response {
    /**
     * 
     * @type {any}
     * @memberof GenreMovieList200Response
     */
    genres?: any | null;
}

/**
 * Check if a given object implements the GenreMovieList200Response interface.
 */
export function instanceOfGenreMovieList200Response(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function GenreMovieList200ResponseFromJSON(json: any): GenreMovieList200Response {
    return GenreMovieList200ResponseFromJSONTyped(json, false);
}

export function GenreMovieList200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GenreMovieList200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'genres': !exists(json, 'genres') ? undefined : json['genres'],
    };
}

export function GenreMovieList200ResponseToJSON(value?: GenreMovieList200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'genres': value.genres,
    };
}

