/* tslint:disable */
/* eslint-disable */
/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ListCheckItemStatus200Response
 */
export interface ListCheckItemStatus200Response {
    /**
     * 
     * @type {any}
     * @memberof ListCheckItemStatus200Response
     */
    id?: any | null;
    /**
     * 
     * @type {any}
     * @memberof ListCheckItemStatus200Response
     */
    itemPresent?: any | null;
}

/**
 * Check if a given object implements the ListCheckItemStatus200Response interface.
 */
export function instanceOfListCheckItemStatus200Response(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ListCheckItemStatus200ResponseFromJSON(json: any): ListCheckItemStatus200Response {
    return ListCheckItemStatus200ResponseFromJSONTyped(json, false);
}

export function ListCheckItemStatus200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListCheckItemStatus200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'itemPresent': !exists(json, 'item_present') ? undefined : json['item_present'],
    };
}

export function ListCheckItemStatus200ResponseToJSON(value?: ListCheckItemStatus200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'item_present': value.itemPresent,
    };
}

