/* tslint:disable */
/* eslint-disable */
/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MovieWatchProviders200ResponseResultsCV
 */
export interface MovieWatchProviders200ResponseResultsCV {
    /**
     * 
     * @type {any}
     * @memberof MovieWatchProviders200ResponseResultsCV
     */
    link?: any | null;
    /**
     * 
     * @type {any}
     * @memberof MovieWatchProviders200ResponseResultsCV
     */
    buy?: any | null;
    /**
     * 
     * @type {any}
     * @memberof MovieWatchProviders200ResponseResultsCV
     */
    rent?: any | null;
}

/**
 * Check if a given object implements the MovieWatchProviders200ResponseResultsCV interface.
 */
export function instanceOfMovieWatchProviders200ResponseResultsCV(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function MovieWatchProviders200ResponseResultsCVFromJSON(json: any): MovieWatchProviders200ResponseResultsCV {
    return MovieWatchProviders200ResponseResultsCVFromJSONTyped(json, false);
}

export function MovieWatchProviders200ResponseResultsCVFromJSONTyped(json: any, ignoreDiscriminator: boolean): MovieWatchProviders200ResponseResultsCV {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'link': !exists(json, 'link') ? undefined : json['link'],
        'buy': !exists(json, 'buy') ? undefined : json['buy'],
        'rent': !exists(json, 'rent') ? undefined : json['rent'],
    };
}

export function MovieWatchProviders200ResponseResultsCVToJSON(value?: MovieWatchProviders200ResponseResultsCV | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'link': value.link,
        'buy': value.buy,
        'rent': value.rent,
    };
}

