/* tslint:disable */
/* eslint-disable */
/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { MovieNowPlayingList200ResponseDates } from './MovieNowPlayingList200ResponseDates';
import {
    MovieNowPlayingList200ResponseDatesFromJSON,
    MovieNowPlayingList200ResponseDatesFromJSONTyped,
    MovieNowPlayingList200ResponseDatesToJSON,
} from './MovieNowPlayingList200ResponseDates';

/**
 * 
 * @export
 * @interface MovieNowPlayingList200Response
 */
export interface MovieNowPlayingList200Response {
    /**
     * 
     * @type {MovieNowPlayingList200ResponseDates}
     * @memberof MovieNowPlayingList200Response
     */
    dates?: MovieNowPlayingList200ResponseDates;
    /**
     * 
     * @type {any}
     * @memberof MovieNowPlayingList200Response
     */
    page?: any | null;
    /**
     * 
     * @type {any}
     * @memberof MovieNowPlayingList200Response
     */
    results?: any | null;
    /**
     * 
     * @type {any}
     * @memberof MovieNowPlayingList200Response
     */
    totalPages?: any | null;
    /**
     * 
     * @type {any}
     * @memberof MovieNowPlayingList200Response
     */
    totalResults?: any | null;
}

/**
 * Check if a given object implements the MovieNowPlayingList200Response interface.
 */
export function instanceOfMovieNowPlayingList200Response(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function MovieNowPlayingList200ResponseFromJSON(json: any): MovieNowPlayingList200Response {
    return MovieNowPlayingList200ResponseFromJSONTyped(json, false);
}

export function MovieNowPlayingList200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): MovieNowPlayingList200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'dates': !exists(json, 'dates') ? undefined : MovieNowPlayingList200ResponseDatesFromJSON(json['dates']),
        'page': !exists(json, 'page') ? undefined : json['page'],
        'results': !exists(json, 'results') ? undefined : json['results'],
        'totalPages': !exists(json, 'total_pages') ? undefined : json['total_pages'],
        'totalResults': !exists(json, 'total_results') ? undefined : json['total_results'],
    };
}

export function MovieNowPlayingList200ResponseToJSON(value?: MovieNowPlayingList200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'dates': MovieNowPlayingList200ResponseDatesToJSON(value.dates),
        'page': value.page,
        'results': value.results,
        'total_pages': value.totalPages,
        'total_results': value.totalResults,
    };
}

