/* tslint:disable */
/* eslint-disable */
/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { MovieAccountStates200ResponseRated } from './MovieAccountStates200ResponseRated';
import {
    MovieAccountStates200ResponseRatedFromJSON,
    MovieAccountStates200ResponseRatedFromJSONTyped,
    MovieAccountStates200ResponseRatedToJSON,
} from './MovieAccountStates200ResponseRated';

/**
 * 
 * @export
 * @interface MovieAccountStates200Response
 */
export interface MovieAccountStates200Response {
    /**
     * 
     * @type {any}
     * @memberof MovieAccountStates200Response
     */
    id?: any | null;
    /**
     * 
     * @type {any}
     * @memberof MovieAccountStates200Response
     */
    favorite?: any | null;
    /**
     * 
     * @type {MovieAccountStates200ResponseRated}
     * @memberof MovieAccountStates200Response
     */
    rated?: MovieAccountStates200ResponseRated;
    /**
     * 
     * @type {any}
     * @memberof MovieAccountStates200Response
     */
    watchlist?: any | null;
}

/**
 * Check if a given object implements the MovieAccountStates200Response interface.
 */
export function instanceOfMovieAccountStates200Response(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function MovieAccountStates200ResponseFromJSON(json: any): MovieAccountStates200Response {
    return MovieAccountStates200ResponseFromJSONTyped(json, false);
}

export function MovieAccountStates200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): MovieAccountStates200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'favorite': !exists(json, 'favorite') ? undefined : json['favorite'],
        'rated': !exists(json, 'rated') ? undefined : MovieAccountStates200ResponseRatedFromJSON(json['rated']),
        'watchlist': !exists(json, 'watchlist') ? undefined : json['watchlist'],
    };
}

export function MovieAccountStates200ResponseToJSON(value?: MovieAccountStates200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'favorite': value.favorite,
        'rated': MovieAccountStates200ResponseRatedToJSON(value.rated),
        'watchlist': value.watchlist,
    };
}

