/* tslint:disable */
/* eslint-disable */
/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MovieNowPlayingList200ResponseDates
 */
export interface MovieNowPlayingList200ResponseDates {
    /**
     * 
     * @type {any}
     * @memberof MovieNowPlayingList200ResponseDates
     */
    maximum?: any | null;
    /**
     * 
     * @type {any}
     * @memberof MovieNowPlayingList200ResponseDates
     */
    minimum?: any | null;
}

/**
 * Check if a given object implements the MovieNowPlayingList200ResponseDates interface.
 */
export function instanceOfMovieNowPlayingList200ResponseDates(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function MovieNowPlayingList200ResponseDatesFromJSON(json: any): MovieNowPlayingList200ResponseDates {
    return MovieNowPlayingList200ResponseDatesFromJSONTyped(json, false);
}

export function MovieNowPlayingList200ResponseDatesFromJSONTyped(json: any, ignoreDiscriminator: boolean): MovieNowPlayingList200ResponseDates {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'maximum': !exists(json, 'maximum') ? undefined : json['maximum'],
        'minimum': !exists(json, 'minimum') ? undefined : json['minimum'],
    };
}

export function MovieNowPlayingList200ResponseDatesToJSON(value?: MovieNowPlayingList200ResponseDates | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'maximum': value.maximum,
        'minimum': value.minimum,
    };
}

