/* tslint:disable */
/* eslint-disable */
/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MovieExternalIds200Response
 */
export interface MovieExternalIds200Response {
    /**
     * 
     * @type {any}
     * @memberof MovieExternalIds200Response
     */
    id?: any | null;
    /**
     * 
     * @type {any}
     * @memberof MovieExternalIds200Response
     */
    imdbId?: any | null;
    /**
     * 
     * @type {any}
     * @memberof MovieExternalIds200Response
     */
    wikidataId?: any | null;
    /**
     * 
     * @type {any}
     * @memberof MovieExternalIds200Response
     */
    facebookId?: any | null;
    /**
     * 
     * @type {any}
     * @memberof MovieExternalIds200Response
     */
    instagramId?: any | null;
    /**
     * 
     * @type {any}
     * @memberof MovieExternalIds200Response
     */
    twitterId?: any | null;
}

/**
 * Check if a given object implements the MovieExternalIds200Response interface.
 */
export function instanceOfMovieExternalIds200Response(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function MovieExternalIds200ResponseFromJSON(json: any): MovieExternalIds200Response {
    return MovieExternalIds200ResponseFromJSONTyped(json, false);
}

export function MovieExternalIds200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): MovieExternalIds200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'imdbId': !exists(json, 'imdb_id') ? undefined : json['imdb_id'],
        'wikidataId': !exists(json, 'wikidata_id') ? undefined : json['wikidata_id'],
        'facebookId': !exists(json, 'facebook_id') ? undefined : json['facebook_id'],
        'instagramId': !exists(json, 'instagram_id') ? undefined : json['instagram_id'],
        'twitterId': !exists(json, 'twitter_id') ? undefined : json['twitter_id'],
    };
}

export function MovieExternalIds200ResponseToJSON(value?: MovieExternalIds200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'imdb_id': value.imdbId,
        'wikidata_id': value.wikidataId,
        'facebook_id': value.facebookId,
        'instagram_id': value.instagramId,
        'twitter_id': value.twitterId,
    };
}

