/* tslint:disable */
/* eslint-disable */
/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TvEpisodeExternalIds200Response
 */
export interface TvEpisodeExternalIds200Response {
    /**
     * 
     * @type {any}
     * @memberof TvEpisodeExternalIds200Response
     */
    id?: any | null;
    /**
     * 
     * @type {any}
     * @memberof TvEpisodeExternalIds200Response
     */
    imdbId?: any | null;
    /**
     * 
     * @type {any}
     * @memberof TvEpisodeExternalIds200Response
     */
    freebaseMid?: any | null;
    /**
     * 
     * @type {any}
     * @memberof TvEpisodeExternalIds200Response
     */
    freebaseId?: any | null;
    /**
     * 
     * @type {any}
     * @memberof TvEpisodeExternalIds200Response
     */
    tvdbId?: any | null;
    /**
     * 
     * @type {any}
     * @memberof TvEpisodeExternalIds200Response
     */
    tvrageId?: any | null;
    /**
     * 
     * @type {any}
     * @memberof TvEpisodeExternalIds200Response
     */
    wikidataId?: any | null;
}

/**
 * Check if a given object implements the TvEpisodeExternalIds200Response interface.
 */
export function instanceOfTvEpisodeExternalIds200Response(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function TvEpisodeExternalIds200ResponseFromJSON(json: any): TvEpisodeExternalIds200Response {
    return TvEpisodeExternalIds200ResponseFromJSONTyped(json, false);
}

export function TvEpisodeExternalIds200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TvEpisodeExternalIds200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'imdbId': !exists(json, 'imdb_id') ? undefined : json['imdb_id'],
        'freebaseMid': !exists(json, 'freebase_mid') ? undefined : json['freebase_mid'],
        'freebaseId': !exists(json, 'freebase_id') ? undefined : json['freebase_id'],
        'tvdbId': !exists(json, 'tvdb_id') ? undefined : json['tvdb_id'],
        'tvrageId': !exists(json, 'tvrage_id') ? undefined : json['tvrage_id'],
        'wikidataId': !exists(json, 'wikidata_id') ? undefined : json['wikidata_id'],
    };
}

export function TvEpisodeExternalIds200ResponseToJSON(value?: TvEpisodeExternalIds200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'imdb_id': value.imdbId,
        'freebase_mid': value.freebaseMid,
        'freebase_id': value.freebaseId,
        'tvdb_id': value.tvdbId,
        'tvrage_id': value.tvrageId,
        'wikidata_id': value.wikidataId,
    };
}

