/* tslint:disable */
/* eslint-disable */
/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TvEpisodeChangesById200Response
 */
export interface TvEpisodeChangesById200Response {
    /**
     * 
     * @type {any}
     * @memberof TvEpisodeChangesById200Response
     */
    changes?: any | null;
}

/**
 * Check if a given object implements the TvEpisodeChangesById200Response interface.
 */
export function instanceOfTvEpisodeChangesById200Response(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function TvEpisodeChangesById200ResponseFromJSON(json: any): TvEpisodeChangesById200Response {
    return TvEpisodeChangesById200ResponseFromJSONTyped(json, false);
}

export function TvEpisodeChangesById200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TvEpisodeChangesById200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'changes': !exists(json, 'changes') ? undefined : json['changes'],
    };
}

export function TvEpisodeChangesById200ResponseToJSON(value?: TvEpisodeChangesById200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'changes': value.changes,
    };
}

