/* tslint:disable */
/* eslint-disable */
/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { TvSeasonWatchProviders200ResponseResultsAE } from './TvSeasonWatchProviders200ResponseResultsAE';
import {
    TvSeasonWatchProviders200ResponseResultsAEFromJSON,
    TvSeasonWatchProviders200ResponseResultsAEFromJSONTyped,
    TvSeasonWatchProviders200ResponseResultsAEToJSON,
} from './TvSeasonWatchProviders200ResponseResultsAE';
import type { TvSeasonWatchProviders200ResponseResultsAR } from './TvSeasonWatchProviders200ResponseResultsAR';
import {
    TvSeasonWatchProviders200ResponseResultsARFromJSON,
    TvSeasonWatchProviders200ResponseResultsARFromJSONTyped,
    TvSeasonWatchProviders200ResponseResultsARToJSON,
} from './TvSeasonWatchProviders200ResponseResultsAR';
import type { TvSeasonWatchProviders200ResponseResultsAT } from './TvSeasonWatchProviders200ResponseResultsAT';
import {
    TvSeasonWatchProviders200ResponseResultsATFromJSON,
    TvSeasonWatchProviders200ResponseResultsATFromJSONTyped,
    TvSeasonWatchProviders200ResponseResultsATToJSON,
} from './TvSeasonWatchProviders200ResponseResultsAT';
import type { TvSeasonWatchProviders200ResponseResultsAU } from './TvSeasonWatchProviders200ResponseResultsAU';
import {
    TvSeasonWatchProviders200ResponseResultsAUFromJSON,
    TvSeasonWatchProviders200ResponseResultsAUFromJSONTyped,
    TvSeasonWatchProviders200ResponseResultsAUToJSON,
} from './TvSeasonWatchProviders200ResponseResultsAU';
import type { TvSeasonWatchProviders200ResponseResultsBA } from './TvSeasonWatchProviders200ResponseResultsBA';
import {
    TvSeasonWatchProviders200ResponseResultsBAFromJSON,
    TvSeasonWatchProviders200ResponseResultsBAFromJSONTyped,
    TvSeasonWatchProviders200ResponseResultsBAToJSON,
} from './TvSeasonWatchProviders200ResponseResultsBA';
import type { TvSeasonWatchProviders200ResponseResultsBB } from './TvSeasonWatchProviders200ResponseResultsBB';
import {
    TvSeasonWatchProviders200ResponseResultsBBFromJSON,
    TvSeasonWatchProviders200ResponseResultsBBFromJSONTyped,
    TvSeasonWatchProviders200ResponseResultsBBToJSON,
} from './TvSeasonWatchProviders200ResponseResultsBB';
import type { TvSeasonWatchProviders200ResponseResultsBE } from './TvSeasonWatchProviders200ResponseResultsBE';
import {
    TvSeasonWatchProviders200ResponseResultsBEFromJSON,
    TvSeasonWatchProviders200ResponseResultsBEFromJSONTyped,
    TvSeasonWatchProviders200ResponseResultsBEToJSON,
} from './TvSeasonWatchProviders200ResponseResultsBE';
import type { TvSeasonWatchProviders200ResponseResultsBG } from './TvSeasonWatchProviders200ResponseResultsBG';
import {
    TvSeasonWatchProviders200ResponseResultsBGFromJSON,
    TvSeasonWatchProviders200ResponseResultsBGFromJSONTyped,
    TvSeasonWatchProviders200ResponseResultsBGToJSON,
} from './TvSeasonWatchProviders200ResponseResultsBG';
import type { TvSeasonWatchProviders200ResponseResultsBO } from './TvSeasonWatchProviders200ResponseResultsBO';
import {
    TvSeasonWatchProviders200ResponseResultsBOFromJSON,
    TvSeasonWatchProviders200ResponseResultsBOFromJSONTyped,
    TvSeasonWatchProviders200ResponseResultsBOToJSON,
} from './TvSeasonWatchProviders200ResponseResultsBO';
import type { TvSeasonWatchProviders200ResponseResultsBR } from './TvSeasonWatchProviders200ResponseResultsBR';
import {
    TvSeasonWatchProviders200ResponseResultsBRFromJSON,
    TvSeasonWatchProviders200ResponseResultsBRFromJSONTyped,
    TvSeasonWatchProviders200ResponseResultsBRToJSON,
} from './TvSeasonWatchProviders200ResponseResultsBR';
import type { TvSeasonWatchProviders200ResponseResultsBS } from './TvSeasonWatchProviders200ResponseResultsBS';
import {
    TvSeasonWatchProviders200ResponseResultsBSFromJSON,
    TvSeasonWatchProviders200ResponseResultsBSFromJSONTyped,
    TvSeasonWatchProviders200ResponseResultsBSToJSON,
} from './TvSeasonWatchProviders200ResponseResultsBS';
import type { TvSeasonWatchProviders200ResponseResultsCA } from './TvSeasonWatchProviders200ResponseResultsCA';
import {
    TvSeasonWatchProviders200ResponseResultsCAFromJSON,
    TvSeasonWatchProviders200ResponseResultsCAFromJSONTyped,
    TvSeasonWatchProviders200ResponseResultsCAToJSON,
} from './TvSeasonWatchProviders200ResponseResultsCA';
import type { TvSeasonWatchProviders200ResponseResultsCH } from './TvSeasonWatchProviders200ResponseResultsCH';
import {
    TvSeasonWatchProviders200ResponseResultsCHFromJSON,
    TvSeasonWatchProviders200ResponseResultsCHFromJSONTyped,
    TvSeasonWatchProviders200ResponseResultsCHToJSON,
} from './TvSeasonWatchProviders200ResponseResultsCH';
import type { TvSeasonWatchProviders200ResponseResultsCI } from './TvSeasonWatchProviders200ResponseResultsCI';
import {
    TvSeasonWatchProviders200ResponseResultsCIFromJSON,
    TvSeasonWatchProviders200ResponseResultsCIFromJSONTyped,
    TvSeasonWatchProviders200ResponseResultsCIToJSON,
} from './TvSeasonWatchProviders200ResponseResultsCI';
import type { TvSeasonWatchProviders200ResponseResultsCL } from './TvSeasonWatchProviders200ResponseResultsCL';
import {
    TvSeasonWatchProviders200ResponseResultsCLFromJSON,
    TvSeasonWatchProviders200ResponseResultsCLFromJSONTyped,
    TvSeasonWatchProviders200ResponseResultsCLToJSON,
} from './TvSeasonWatchProviders200ResponseResultsCL';
import type { TvSeasonWatchProviders200ResponseResultsCO } from './TvSeasonWatchProviders200ResponseResultsCO';
import {
    TvSeasonWatchProviders200ResponseResultsCOFromJSON,
    TvSeasonWatchProviders200ResponseResultsCOFromJSONTyped,
    TvSeasonWatchProviders200ResponseResultsCOToJSON,
} from './TvSeasonWatchProviders200ResponseResultsCO';
import type { TvSeasonWatchProviders200ResponseResultsCR } from './TvSeasonWatchProviders200ResponseResultsCR';
import {
    TvSeasonWatchProviders200ResponseResultsCRFromJSON,
    TvSeasonWatchProviders200ResponseResultsCRFromJSONTyped,
    TvSeasonWatchProviders200ResponseResultsCRToJSON,
} from './TvSeasonWatchProviders200ResponseResultsCR';
import type { TvSeasonWatchProviders200ResponseResultsCZ } from './TvSeasonWatchProviders200ResponseResultsCZ';
import {
    TvSeasonWatchProviders200ResponseResultsCZFromJSON,
    TvSeasonWatchProviders200ResponseResultsCZFromJSONTyped,
    TvSeasonWatchProviders200ResponseResultsCZToJSON,
} from './TvSeasonWatchProviders200ResponseResultsCZ';
import type { TvSeasonWatchProviders200ResponseResultsDE } from './TvSeasonWatchProviders200ResponseResultsDE';
import {
    TvSeasonWatchProviders200ResponseResultsDEFromJSON,
    TvSeasonWatchProviders200ResponseResultsDEFromJSONTyped,
    TvSeasonWatchProviders200ResponseResultsDEToJSON,
} from './TvSeasonWatchProviders200ResponseResultsDE';
import type { TvSeasonWatchProviders200ResponseResultsDK } from './TvSeasonWatchProviders200ResponseResultsDK';
import {
    TvSeasonWatchProviders200ResponseResultsDKFromJSON,
    TvSeasonWatchProviders200ResponseResultsDKFromJSONTyped,
    TvSeasonWatchProviders200ResponseResultsDKToJSON,
} from './TvSeasonWatchProviders200ResponseResultsDK';
import type { TvSeasonWatchProviders200ResponseResultsDO } from './TvSeasonWatchProviders200ResponseResultsDO';
import {
    TvSeasonWatchProviders200ResponseResultsDOFromJSON,
    TvSeasonWatchProviders200ResponseResultsDOFromJSONTyped,
    TvSeasonWatchProviders200ResponseResultsDOToJSON,
} from './TvSeasonWatchProviders200ResponseResultsDO';
import type { TvSeasonWatchProviders200ResponseResultsDZ } from './TvSeasonWatchProviders200ResponseResultsDZ';
import {
    TvSeasonWatchProviders200ResponseResultsDZFromJSON,
    TvSeasonWatchProviders200ResponseResultsDZFromJSONTyped,
    TvSeasonWatchProviders200ResponseResultsDZToJSON,
} from './TvSeasonWatchProviders200ResponseResultsDZ';
import type { TvSeasonWatchProviders200ResponseResultsEC } from './TvSeasonWatchProviders200ResponseResultsEC';
import {
    TvSeasonWatchProviders200ResponseResultsECFromJSON,
    TvSeasonWatchProviders200ResponseResultsECFromJSONTyped,
    TvSeasonWatchProviders200ResponseResultsECToJSON,
} from './TvSeasonWatchProviders200ResponseResultsEC';
import type { TvSeasonWatchProviders200ResponseResultsEG } from './TvSeasonWatchProviders200ResponseResultsEG';
import {
    TvSeasonWatchProviders200ResponseResultsEGFromJSON,
    TvSeasonWatchProviders200ResponseResultsEGFromJSONTyped,
    TvSeasonWatchProviders200ResponseResultsEGToJSON,
} from './TvSeasonWatchProviders200ResponseResultsEG';
import type { TvSeasonWatchProviders200ResponseResultsES } from './TvSeasonWatchProviders200ResponseResultsES';
import {
    TvSeasonWatchProviders200ResponseResultsESFromJSON,
    TvSeasonWatchProviders200ResponseResultsESFromJSONTyped,
    TvSeasonWatchProviders200ResponseResultsESToJSON,
} from './TvSeasonWatchProviders200ResponseResultsES';
import type { TvSeasonWatchProviders200ResponseResultsFI } from './TvSeasonWatchProviders200ResponseResultsFI';
import {
    TvSeasonWatchProviders200ResponseResultsFIFromJSON,
    TvSeasonWatchProviders200ResponseResultsFIFromJSONTyped,
    TvSeasonWatchProviders200ResponseResultsFIToJSON,
} from './TvSeasonWatchProviders200ResponseResultsFI';
import type { TvSeasonWatchProviders200ResponseResultsFR } from './TvSeasonWatchProviders200ResponseResultsFR';
import {
    TvSeasonWatchProviders200ResponseResultsFRFromJSON,
    TvSeasonWatchProviders200ResponseResultsFRFromJSONTyped,
    TvSeasonWatchProviders200ResponseResultsFRToJSON,
} from './TvSeasonWatchProviders200ResponseResultsFR';
import type { TvSeasonWatchProviders200ResponseResultsGB } from './TvSeasonWatchProviders200ResponseResultsGB';
import {
    TvSeasonWatchProviders200ResponseResultsGBFromJSON,
    TvSeasonWatchProviders200ResponseResultsGBFromJSONTyped,
    TvSeasonWatchProviders200ResponseResultsGBToJSON,
} from './TvSeasonWatchProviders200ResponseResultsGB';
import type { TvSeasonWatchProviders200ResponseResultsGF } from './TvSeasonWatchProviders200ResponseResultsGF';
import {
    TvSeasonWatchProviders200ResponseResultsGFFromJSON,
    TvSeasonWatchProviders200ResponseResultsGFFromJSONTyped,
    TvSeasonWatchProviders200ResponseResultsGFToJSON,
} from './TvSeasonWatchProviders200ResponseResultsGF';
import type { TvSeasonWatchProviders200ResponseResultsGH } from './TvSeasonWatchProviders200ResponseResultsGH';
import {
    TvSeasonWatchProviders200ResponseResultsGHFromJSON,
    TvSeasonWatchProviders200ResponseResultsGHFromJSONTyped,
    TvSeasonWatchProviders200ResponseResultsGHToJSON,
} from './TvSeasonWatchProviders200ResponseResultsGH';
import type { TvSeasonWatchProviders200ResponseResultsGQ } from './TvSeasonWatchProviders200ResponseResultsGQ';
import {
    TvSeasonWatchProviders200ResponseResultsGQFromJSON,
    TvSeasonWatchProviders200ResponseResultsGQFromJSONTyped,
    TvSeasonWatchProviders200ResponseResultsGQToJSON,
} from './TvSeasonWatchProviders200ResponseResultsGQ';
import type { TvSeasonWatchProviders200ResponseResultsGT } from './TvSeasonWatchProviders200ResponseResultsGT';
import {
    TvSeasonWatchProviders200ResponseResultsGTFromJSON,
    TvSeasonWatchProviders200ResponseResultsGTFromJSONTyped,
    TvSeasonWatchProviders200ResponseResultsGTToJSON,
} from './TvSeasonWatchProviders200ResponseResultsGT';
import type { TvSeasonWatchProviders200ResponseResultsHK } from './TvSeasonWatchProviders200ResponseResultsHK';
import {
    TvSeasonWatchProviders200ResponseResultsHKFromJSON,
    TvSeasonWatchProviders200ResponseResultsHKFromJSONTyped,
    TvSeasonWatchProviders200ResponseResultsHKToJSON,
} from './TvSeasonWatchProviders200ResponseResultsHK';
import type { TvSeasonWatchProviders200ResponseResultsHN } from './TvSeasonWatchProviders200ResponseResultsHN';
import {
    TvSeasonWatchProviders200ResponseResultsHNFromJSON,
    TvSeasonWatchProviders200ResponseResultsHNFromJSONTyped,
    TvSeasonWatchProviders200ResponseResultsHNToJSON,
} from './TvSeasonWatchProviders200ResponseResultsHN';
import type { TvSeasonWatchProviders200ResponseResultsHR } from './TvSeasonWatchProviders200ResponseResultsHR';
import {
    TvSeasonWatchProviders200ResponseResultsHRFromJSON,
    TvSeasonWatchProviders200ResponseResultsHRFromJSONTyped,
    TvSeasonWatchProviders200ResponseResultsHRToJSON,
} from './TvSeasonWatchProviders200ResponseResultsHR';
import type { TvSeasonWatchProviders200ResponseResultsHU } from './TvSeasonWatchProviders200ResponseResultsHU';
import {
    TvSeasonWatchProviders200ResponseResultsHUFromJSON,
    TvSeasonWatchProviders200ResponseResultsHUFromJSONTyped,
    TvSeasonWatchProviders200ResponseResultsHUToJSON,
} from './TvSeasonWatchProviders200ResponseResultsHU';
import type { TvSeasonWatchProviders200ResponseResultsID } from './TvSeasonWatchProviders200ResponseResultsID';
import {
    TvSeasonWatchProviders200ResponseResultsIDFromJSON,
    TvSeasonWatchProviders200ResponseResultsIDFromJSONTyped,
    TvSeasonWatchProviders200ResponseResultsIDToJSON,
} from './TvSeasonWatchProviders200ResponseResultsID';
import type { TvSeasonWatchProviders200ResponseResultsIE } from './TvSeasonWatchProviders200ResponseResultsIE';
import {
    TvSeasonWatchProviders200ResponseResultsIEFromJSON,
    TvSeasonWatchProviders200ResponseResultsIEFromJSONTyped,
    TvSeasonWatchProviders200ResponseResultsIEToJSON,
} from './TvSeasonWatchProviders200ResponseResultsIE';
import type { TvSeasonWatchProviders200ResponseResultsIL } from './TvSeasonWatchProviders200ResponseResultsIL';
import {
    TvSeasonWatchProviders200ResponseResultsILFromJSON,
    TvSeasonWatchProviders200ResponseResultsILFromJSONTyped,
    TvSeasonWatchProviders200ResponseResultsILToJSON,
} from './TvSeasonWatchProviders200ResponseResultsIL';
import type { TvSeasonWatchProviders200ResponseResultsIQ } from './TvSeasonWatchProviders200ResponseResultsIQ';
import {
    TvSeasonWatchProviders200ResponseResultsIQFromJSON,
    TvSeasonWatchProviders200ResponseResultsIQFromJSONTyped,
    TvSeasonWatchProviders200ResponseResultsIQToJSON,
} from './TvSeasonWatchProviders200ResponseResultsIQ';
import type { TvSeasonWatchProviders200ResponseResultsIT } from './TvSeasonWatchProviders200ResponseResultsIT';
import {
    TvSeasonWatchProviders200ResponseResultsITFromJSON,
    TvSeasonWatchProviders200ResponseResultsITFromJSONTyped,
    TvSeasonWatchProviders200ResponseResultsITToJSON,
} from './TvSeasonWatchProviders200ResponseResultsIT';
import type { TvSeasonWatchProviders200ResponseResultsJM } from './TvSeasonWatchProviders200ResponseResultsJM';
import {
    TvSeasonWatchProviders200ResponseResultsJMFromJSON,
    TvSeasonWatchProviders200ResponseResultsJMFromJSONTyped,
    TvSeasonWatchProviders200ResponseResultsJMToJSON,
} from './TvSeasonWatchProviders200ResponseResultsJM';
import type { TvSeasonWatchProviders200ResponseResultsJP } from './TvSeasonWatchProviders200ResponseResultsJP';
import {
    TvSeasonWatchProviders200ResponseResultsJPFromJSON,
    TvSeasonWatchProviders200ResponseResultsJPFromJSONTyped,
    TvSeasonWatchProviders200ResponseResultsJPToJSON,
} from './TvSeasonWatchProviders200ResponseResultsJP';
import type { TvSeasonWatchProviders200ResponseResultsKE } from './TvSeasonWatchProviders200ResponseResultsKE';
import {
    TvSeasonWatchProviders200ResponseResultsKEFromJSON,
    TvSeasonWatchProviders200ResponseResultsKEFromJSONTyped,
    TvSeasonWatchProviders200ResponseResultsKEToJSON,
} from './TvSeasonWatchProviders200ResponseResultsKE';
import type { TvSeasonWatchProviders200ResponseResultsKR } from './TvSeasonWatchProviders200ResponseResultsKR';
import {
    TvSeasonWatchProviders200ResponseResultsKRFromJSON,
    TvSeasonWatchProviders200ResponseResultsKRFromJSONTyped,
    TvSeasonWatchProviders200ResponseResultsKRToJSON,
} from './TvSeasonWatchProviders200ResponseResultsKR';
import type { TvSeasonWatchProviders200ResponseResultsLB } from './TvSeasonWatchProviders200ResponseResultsLB';
import {
    TvSeasonWatchProviders200ResponseResultsLBFromJSON,
    TvSeasonWatchProviders200ResponseResultsLBFromJSONTyped,
    TvSeasonWatchProviders200ResponseResultsLBToJSON,
} from './TvSeasonWatchProviders200ResponseResultsLB';
import type { TvSeasonWatchProviders200ResponseResultsLY } from './TvSeasonWatchProviders200ResponseResultsLY';
import {
    TvSeasonWatchProviders200ResponseResultsLYFromJSON,
    TvSeasonWatchProviders200ResponseResultsLYFromJSONTyped,
    TvSeasonWatchProviders200ResponseResultsLYToJSON,
} from './TvSeasonWatchProviders200ResponseResultsLY';
import type { TvSeasonWatchProviders200ResponseResultsMD } from './TvSeasonWatchProviders200ResponseResultsMD';
import {
    TvSeasonWatchProviders200ResponseResultsMDFromJSON,
    TvSeasonWatchProviders200ResponseResultsMDFromJSONTyped,
    TvSeasonWatchProviders200ResponseResultsMDToJSON,
} from './TvSeasonWatchProviders200ResponseResultsMD';
import type { TvSeasonWatchProviders200ResponseResultsMK } from './TvSeasonWatchProviders200ResponseResultsMK';
import {
    TvSeasonWatchProviders200ResponseResultsMKFromJSON,
    TvSeasonWatchProviders200ResponseResultsMKFromJSONTyped,
    TvSeasonWatchProviders200ResponseResultsMKToJSON,
} from './TvSeasonWatchProviders200ResponseResultsMK';
import type { TvSeasonWatchProviders200ResponseResultsMU } from './TvSeasonWatchProviders200ResponseResultsMU';
import {
    TvSeasonWatchProviders200ResponseResultsMUFromJSON,
    TvSeasonWatchProviders200ResponseResultsMUFromJSONTyped,
    TvSeasonWatchProviders200ResponseResultsMUToJSON,
} from './TvSeasonWatchProviders200ResponseResultsMU';
import type { TvSeasonWatchProviders200ResponseResultsMX } from './TvSeasonWatchProviders200ResponseResultsMX';
import {
    TvSeasonWatchProviders200ResponseResultsMXFromJSON,
    TvSeasonWatchProviders200ResponseResultsMXFromJSONTyped,
    TvSeasonWatchProviders200ResponseResultsMXToJSON,
} from './TvSeasonWatchProviders200ResponseResultsMX';
import type { TvSeasonWatchProviders200ResponseResultsMY } from './TvSeasonWatchProviders200ResponseResultsMY';
import {
    TvSeasonWatchProviders200ResponseResultsMYFromJSON,
    TvSeasonWatchProviders200ResponseResultsMYFromJSONTyped,
    TvSeasonWatchProviders200ResponseResultsMYToJSON,
} from './TvSeasonWatchProviders200ResponseResultsMY';
import type { TvSeasonWatchProviders200ResponseResultsMZ } from './TvSeasonWatchProviders200ResponseResultsMZ';
import {
    TvSeasonWatchProviders200ResponseResultsMZFromJSON,
    TvSeasonWatchProviders200ResponseResultsMZFromJSONTyped,
    TvSeasonWatchProviders200ResponseResultsMZToJSON,
} from './TvSeasonWatchProviders200ResponseResultsMZ';
import type { TvSeasonWatchProviders200ResponseResultsNE } from './TvSeasonWatchProviders200ResponseResultsNE';
import {
    TvSeasonWatchProviders200ResponseResultsNEFromJSON,
    TvSeasonWatchProviders200ResponseResultsNEFromJSONTyped,
    TvSeasonWatchProviders200ResponseResultsNEToJSON,
} from './TvSeasonWatchProviders200ResponseResultsNE';
import type { TvSeasonWatchProviders200ResponseResultsNG } from './TvSeasonWatchProviders200ResponseResultsNG';
import {
    TvSeasonWatchProviders200ResponseResultsNGFromJSON,
    TvSeasonWatchProviders200ResponseResultsNGFromJSONTyped,
    TvSeasonWatchProviders200ResponseResultsNGToJSON,
} from './TvSeasonWatchProviders200ResponseResultsNG';
import type { TvSeasonWatchProviders200ResponseResultsNL } from './TvSeasonWatchProviders200ResponseResultsNL';
import {
    TvSeasonWatchProviders200ResponseResultsNLFromJSON,
    TvSeasonWatchProviders200ResponseResultsNLFromJSONTyped,
    TvSeasonWatchProviders200ResponseResultsNLToJSON,
} from './TvSeasonWatchProviders200ResponseResultsNL';
import type { TvSeasonWatchProviders200ResponseResultsNO } from './TvSeasonWatchProviders200ResponseResultsNO';
import {
    TvSeasonWatchProviders200ResponseResultsNOFromJSON,
    TvSeasonWatchProviders200ResponseResultsNOFromJSONTyped,
    TvSeasonWatchProviders200ResponseResultsNOToJSON,
} from './TvSeasonWatchProviders200ResponseResultsNO';
import type { TvSeasonWatchProviders200ResponseResultsNZ } from './TvSeasonWatchProviders200ResponseResultsNZ';
import {
    TvSeasonWatchProviders200ResponseResultsNZFromJSON,
    TvSeasonWatchProviders200ResponseResultsNZFromJSONTyped,
    TvSeasonWatchProviders200ResponseResultsNZToJSON,
} from './TvSeasonWatchProviders200ResponseResultsNZ';
import type { TvSeasonWatchProviders200ResponseResultsPA } from './TvSeasonWatchProviders200ResponseResultsPA';
import {
    TvSeasonWatchProviders200ResponseResultsPAFromJSON,
    TvSeasonWatchProviders200ResponseResultsPAFromJSONTyped,
    TvSeasonWatchProviders200ResponseResultsPAToJSON,
} from './TvSeasonWatchProviders200ResponseResultsPA';
import type { TvSeasonWatchProviders200ResponseResultsPE } from './TvSeasonWatchProviders200ResponseResultsPE';
import {
    TvSeasonWatchProviders200ResponseResultsPEFromJSON,
    TvSeasonWatchProviders200ResponseResultsPEFromJSONTyped,
    TvSeasonWatchProviders200ResponseResultsPEToJSON,
} from './TvSeasonWatchProviders200ResponseResultsPE';
import type { TvSeasonWatchProviders200ResponseResultsPH } from './TvSeasonWatchProviders200ResponseResultsPH';
import {
    TvSeasonWatchProviders200ResponseResultsPHFromJSON,
    TvSeasonWatchProviders200ResponseResultsPHFromJSONTyped,
    TvSeasonWatchProviders200ResponseResultsPHToJSON,
} from './TvSeasonWatchProviders200ResponseResultsPH';
import type { TvSeasonWatchProviders200ResponseResultsPL } from './TvSeasonWatchProviders200ResponseResultsPL';
import {
    TvSeasonWatchProviders200ResponseResultsPLFromJSON,
    TvSeasonWatchProviders200ResponseResultsPLFromJSONTyped,
    TvSeasonWatchProviders200ResponseResultsPLToJSON,
} from './TvSeasonWatchProviders200ResponseResultsPL';
import type { TvSeasonWatchProviders200ResponseResultsPS } from './TvSeasonWatchProviders200ResponseResultsPS';
import {
    TvSeasonWatchProviders200ResponseResultsPSFromJSON,
    TvSeasonWatchProviders200ResponseResultsPSFromJSONTyped,
    TvSeasonWatchProviders200ResponseResultsPSToJSON,
} from './TvSeasonWatchProviders200ResponseResultsPS';
import type { TvSeasonWatchProviders200ResponseResultsPT } from './TvSeasonWatchProviders200ResponseResultsPT';
import {
    TvSeasonWatchProviders200ResponseResultsPTFromJSON,
    TvSeasonWatchProviders200ResponseResultsPTFromJSONTyped,
    TvSeasonWatchProviders200ResponseResultsPTToJSON,
} from './TvSeasonWatchProviders200ResponseResultsPT';
import type { TvSeasonWatchProviders200ResponseResultsPY } from './TvSeasonWatchProviders200ResponseResultsPY';
import {
    TvSeasonWatchProviders200ResponseResultsPYFromJSON,
    TvSeasonWatchProviders200ResponseResultsPYFromJSONTyped,
    TvSeasonWatchProviders200ResponseResultsPYToJSON,
} from './TvSeasonWatchProviders200ResponseResultsPY';
import type { TvSeasonWatchProviders200ResponseResultsRO } from './TvSeasonWatchProviders200ResponseResultsRO';
import {
    TvSeasonWatchProviders200ResponseResultsROFromJSON,
    TvSeasonWatchProviders200ResponseResultsROFromJSONTyped,
    TvSeasonWatchProviders200ResponseResultsROToJSON,
} from './TvSeasonWatchProviders200ResponseResultsRO';
import type { TvSeasonWatchProviders200ResponseResultsRS } from './TvSeasonWatchProviders200ResponseResultsRS';
import {
    TvSeasonWatchProviders200ResponseResultsRSFromJSON,
    TvSeasonWatchProviders200ResponseResultsRSFromJSONTyped,
    TvSeasonWatchProviders200ResponseResultsRSToJSON,
} from './TvSeasonWatchProviders200ResponseResultsRS';
import type { TvSeasonWatchProviders200ResponseResultsRU } from './TvSeasonWatchProviders200ResponseResultsRU';
import {
    TvSeasonWatchProviders200ResponseResultsRUFromJSON,
    TvSeasonWatchProviders200ResponseResultsRUFromJSONTyped,
    TvSeasonWatchProviders200ResponseResultsRUToJSON,
} from './TvSeasonWatchProviders200ResponseResultsRU';
import type { TvSeasonWatchProviders200ResponseResultsSA } from './TvSeasonWatchProviders200ResponseResultsSA';
import {
    TvSeasonWatchProviders200ResponseResultsSAFromJSON,
    TvSeasonWatchProviders200ResponseResultsSAFromJSONTyped,
    TvSeasonWatchProviders200ResponseResultsSAToJSON,
} from './TvSeasonWatchProviders200ResponseResultsSA';
import type { TvSeasonWatchProviders200ResponseResultsSC } from './TvSeasonWatchProviders200ResponseResultsSC';
import {
    TvSeasonWatchProviders200ResponseResultsSCFromJSON,
    TvSeasonWatchProviders200ResponseResultsSCFromJSONTyped,
    TvSeasonWatchProviders200ResponseResultsSCToJSON,
} from './TvSeasonWatchProviders200ResponseResultsSC';
import type { TvSeasonWatchProviders200ResponseResultsSE } from './TvSeasonWatchProviders200ResponseResultsSE';
import {
    TvSeasonWatchProviders200ResponseResultsSEFromJSON,
    TvSeasonWatchProviders200ResponseResultsSEFromJSONTyped,
    TvSeasonWatchProviders200ResponseResultsSEToJSON,
} from './TvSeasonWatchProviders200ResponseResultsSE';
import type { TvSeasonWatchProviders200ResponseResultsSG } from './TvSeasonWatchProviders200ResponseResultsSG';
import {
    TvSeasonWatchProviders200ResponseResultsSGFromJSON,
    TvSeasonWatchProviders200ResponseResultsSGFromJSONTyped,
    TvSeasonWatchProviders200ResponseResultsSGToJSON,
} from './TvSeasonWatchProviders200ResponseResultsSG';
import type { TvSeasonWatchProviders200ResponseResultsSI } from './TvSeasonWatchProviders200ResponseResultsSI';
import {
    TvSeasonWatchProviders200ResponseResultsSIFromJSON,
    TvSeasonWatchProviders200ResponseResultsSIFromJSONTyped,
    TvSeasonWatchProviders200ResponseResultsSIToJSON,
} from './TvSeasonWatchProviders200ResponseResultsSI';
import type { TvSeasonWatchProviders200ResponseResultsSK } from './TvSeasonWatchProviders200ResponseResultsSK';
import {
    TvSeasonWatchProviders200ResponseResultsSKFromJSON,
    TvSeasonWatchProviders200ResponseResultsSKFromJSONTyped,
    TvSeasonWatchProviders200ResponseResultsSKToJSON,
} from './TvSeasonWatchProviders200ResponseResultsSK';
import type { TvSeasonWatchProviders200ResponseResultsSN } from './TvSeasonWatchProviders200ResponseResultsSN';
import {
    TvSeasonWatchProviders200ResponseResultsSNFromJSON,
    TvSeasonWatchProviders200ResponseResultsSNFromJSONTyped,
    TvSeasonWatchProviders200ResponseResultsSNToJSON,
} from './TvSeasonWatchProviders200ResponseResultsSN';
import type { TvSeasonWatchProviders200ResponseResultsSV } from './TvSeasonWatchProviders200ResponseResultsSV';
import {
    TvSeasonWatchProviders200ResponseResultsSVFromJSON,
    TvSeasonWatchProviders200ResponseResultsSVFromJSONTyped,
    TvSeasonWatchProviders200ResponseResultsSVToJSON,
} from './TvSeasonWatchProviders200ResponseResultsSV';
import type { TvSeasonWatchProviders200ResponseResultsTH } from './TvSeasonWatchProviders200ResponseResultsTH';
import {
    TvSeasonWatchProviders200ResponseResultsTHFromJSON,
    TvSeasonWatchProviders200ResponseResultsTHFromJSONTyped,
    TvSeasonWatchProviders200ResponseResultsTHToJSON,
} from './TvSeasonWatchProviders200ResponseResultsTH';
import type { TvSeasonWatchProviders200ResponseResultsTR } from './TvSeasonWatchProviders200ResponseResultsTR';
import {
    TvSeasonWatchProviders200ResponseResultsTRFromJSON,
    TvSeasonWatchProviders200ResponseResultsTRFromJSONTyped,
    TvSeasonWatchProviders200ResponseResultsTRToJSON,
} from './TvSeasonWatchProviders200ResponseResultsTR';
import type { TvSeasonWatchProviders200ResponseResultsTT } from './TvSeasonWatchProviders200ResponseResultsTT';
import {
    TvSeasonWatchProviders200ResponseResultsTTFromJSON,
    TvSeasonWatchProviders200ResponseResultsTTFromJSONTyped,
    TvSeasonWatchProviders200ResponseResultsTTToJSON,
} from './TvSeasonWatchProviders200ResponseResultsTT';
import type { TvSeasonWatchProviders200ResponseResultsTW } from './TvSeasonWatchProviders200ResponseResultsTW';
import {
    TvSeasonWatchProviders200ResponseResultsTWFromJSON,
    TvSeasonWatchProviders200ResponseResultsTWFromJSONTyped,
    TvSeasonWatchProviders200ResponseResultsTWToJSON,
} from './TvSeasonWatchProviders200ResponseResultsTW';
import type { TvSeasonWatchProviders200ResponseResultsTZ } from './TvSeasonWatchProviders200ResponseResultsTZ';
import {
    TvSeasonWatchProviders200ResponseResultsTZFromJSON,
    TvSeasonWatchProviders200ResponseResultsTZFromJSONTyped,
    TvSeasonWatchProviders200ResponseResultsTZToJSON,
} from './TvSeasonWatchProviders200ResponseResultsTZ';
import type { TvSeasonWatchProviders200ResponseResultsUG } from './TvSeasonWatchProviders200ResponseResultsUG';
import {
    TvSeasonWatchProviders200ResponseResultsUGFromJSON,
    TvSeasonWatchProviders200ResponseResultsUGFromJSONTyped,
    TvSeasonWatchProviders200ResponseResultsUGToJSON,
} from './TvSeasonWatchProviders200ResponseResultsUG';
import type { TvSeasonWatchProviders200ResponseResultsUS } from './TvSeasonWatchProviders200ResponseResultsUS';
import {
    TvSeasonWatchProviders200ResponseResultsUSFromJSON,
    TvSeasonWatchProviders200ResponseResultsUSFromJSONTyped,
    TvSeasonWatchProviders200ResponseResultsUSToJSON,
} from './TvSeasonWatchProviders200ResponseResultsUS';
import type { TvSeasonWatchProviders200ResponseResultsUY } from './TvSeasonWatchProviders200ResponseResultsUY';
import {
    TvSeasonWatchProviders200ResponseResultsUYFromJSON,
    TvSeasonWatchProviders200ResponseResultsUYFromJSONTyped,
    TvSeasonWatchProviders200ResponseResultsUYToJSON,
} from './TvSeasonWatchProviders200ResponseResultsUY';
import type { TvSeasonWatchProviders200ResponseResultsVE } from './TvSeasonWatchProviders200ResponseResultsVE';
import {
    TvSeasonWatchProviders200ResponseResultsVEFromJSON,
    TvSeasonWatchProviders200ResponseResultsVEFromJSONTyped,
    TvSeasonWatchProviders200ResponseResultsVEToJSON,
} from './TvSeasonWatchProviders200ResponseResultsVE';
import type { TvSeasonWatchProviders200ResponseResultsZA } from './TvSeasonWatchProviders200ResponseResultsZA';
import {
    TvSeasonWatchProviders200ResponseResultsZAFromJSON,
    TvSeasonWatchProviders200ResponseResultsZAFromJSONTyped,
    TvSeasonWatchProviders200ResponseResultsZAToJSON,
} from './TvSeasonWatchProviders200ResponseResultsZA';
import type { TvSeasonWatchProviders200ResponseResultsZM } from './TvSeasonWatchProviders200ResponseResultsZM';
import {
    TvSeasonWatchProviders200ResponseResultsZMFromJSON,
    TvSeasonWatchProviders200ResponseResultsZMFromJSONTyped,
    TvSeasonWatchProviders200ResponseResultsZMToJSON,
} from './TvSeasonWatchProviders200ResponseResultsZM';

/**
 * 
 * @export
 * @interface TvSeasonWatchProviders200ResponseResults
 */
export interface TvSeasonWatchProviders200ResponseResults {
    /**
     * 
     * @type {TvSeasonWatchProviders200ResponseResultsAE}
     * @memberof TvSeasonWatchProviders200ResponseResults
     */
    aE?: TvSeasonWatchProviders200ResponseResultsAE;
    /**
     * 
     * @type {TvSeasonWatchProviders200ResponseResultsAR}
     * @memberof TvSeasonWatchProviders200ResponseResults
     */
    aR?: TvSeasonWatchProviders200ResponseResultsAR;
    /**
     * 
     * @type {TvSeasonWatchProviders200ResponseResultsAT}
     * @memberof TvSeasonWatchProviders200ResponseResults
     */
    aT?: TvSeasonWatchProviders200ResponseResultsAT;
    /**
     * 
     * @type {TvSeasonWatchProviders200ResponseResultsAU}
     * @memberof TvSeasonWatchProviders200ResponseResults
     */
    aU?: TvSeasonWatchProviders200ResponseResultsAU;
    /**
     * 
     * @type {TvSeasonWatchProviders200ResponseResultsBA}
     * @memberof TvSeasonWatchProviders200ResponseResults
     */
    bA?: TvSeasonWatchProviders200ResponseResultsBA;
    /**
     * 
     * @type {TvSeasonWatchProviders200ResponseResultsBB}
     * @memberof TvSeasonWatchProviders200ResponseResults
     */
    bB?: TvSeasonWatchProviders200ResponseResultsBB;
    /**
     * 
     * @type {TvSeasonWatchProviders200ResponseResultsBE}
     * @memberof TvSeasonWatchProviders200ResponseResults
     */
    bE?: TvSeasonWatchProviders200ResponseResultsBE;
    /**
     * 
     * @type {TvSeasonWatchProviders200ResponseResultsBG}
     * @memberof TvSeasonWatchProviders200ResponseResults
     */
    bG?: TvSeasonWatchProviders200ResponseResultsBG;
    /**
     * 
     * @type {TvSeasonWatchProviders200ResponseResultsBO}
     * @memberof TvSeasonWatchProviders200ResponseResults
     */
    bO?: TvSeasonWatchProviders200ResponseResultsBO;
    /**
     * 
     * @type {TvSeasonWatchProviders200ResponseResultsBR}
     * @memberof TvSeasonWatchProviders200ResponseResults
     */
    bR?: TvSeasonWatchProviders200ResponseResultsBR;
    /**
     * 
     * @type {TvSeasonWatchProviders200ResponseResultsBS}
     * @memberof TvSeasonWatchProviders200ResponseResults
     */
    bS?: TvSeasonWatchProviders200ResponseResultsBS;
    /**
     * 
     * @type {TvSeasonWatchProviders200ResponseResultsCA}
     * @memberof TvSeasonWatchProviders200ResponseResults
     */
    cA?: TvSeasonWatchProviders200ResponseResultsCA;
    /**
     * 
     * @type {TvSeasonWatchProviders200ResponseResultsCH}
     * @memberof TvSeasonWatchProviders200ResponseResults
     */
    cH?: TvSeasonWatchProviders200ResponseResultsCH;
    /**
     * 
     * @type {TvSeasonWatchProviders200ResponseResultsCI}
     * @memberof TvSeasonWatchProviders200ResponseResults
     */
    cI?: TvSeasonWatchProviders200ResponseResultsCI;
    /**
     * 
     * @type {TvSeasonWatchProviders200ResponseResultsCL}
     * @memberof TvSeasonWatchProviders200ResponseResults
     */
    cL?: TvSeasonWatchProviders200ResponseResultsCL;
    /**
     * 
     * @type {TvSeasonWatchProviders200ResponseResultsCO}
     * @memberof TvSeasonWatchProviders200ResponseResults
     */
    cO?: TvSeasonWatchProviders200ResponseResultsCO;
    /**
     * 
     * @type {TvSeasonWatchProviders200ResponseResultsCR}
     * @memberof TvSeasonWatchProviders200ResponseResults
     */
    cR?: TvSeasonWatchProviders200ResponseResultsCR;
    /**
     * 
     * @type {TvSeasonWatchProviders200ResponseResultsCZ}
     * @memberof TvSeasonWatchProviders200ResponseResults
     */
    cZ?: TvSeasonWatchProviders200ResponseResultsCZ;
    /**
     * 
     * @type {TvSeasonWatchProviders200ResponseResultsDE}
     * @memberof TvSeasonWatchProviders200ResponseResults
     */
    dE?: TvSeasonWatchProviders200ResponseResultsDE;
    /**
     * 
     * @type {TvSeasonWatchProviders200ResponseResultsDK}
     * @memberof TvSeasonWatchProviders200ResponseResults
     */
    dK?: TvSeasonWatchProviders200ResponseResultsDK;
    /**
     * 
     * @type {TvSeasonWatchProviders200ResponseResultsDO}
     * @memberof TvSeasonWatchProviders200ResponseResults
     */
    dO?: TvSeasonWatchProviders200ResponseResultsDO;
    /**
     * 
     * @type {TvSeasonWatchProviders200ResponseResultsDZ}
     * @memberof TvSeasonWatchProviders200ResponseResults
     */
    dZ?: TvSeasonWatchProviders200ResponseResultsDZ;
    /**
     * 
     * @type {TvSeasonWatchProviders200ResponseResultsEC}
     * @memberof TvSeasonWatchProviders200ResponseResults
     */
    eC?: TvSeasonWatchProviders200ResponseResultsEC;
    /**
     * 
     * @type {TvSeasonWatchProviders200ResponseResultsEG}
     * @memberof TvSeasonWatchProviders200ResponseResults
     */
    eG?: TvSeasonWatchProviders200ResponseResultsEG;
    /**
     * 
     * @type {TvSeasonWatchProviders200ResponseResultsES}
     * @memberof TvSeasonWatchProviders200ResponseResults
     */
    eS?: TvSeasonWatchProviders200ResponseResultsES;
    /**
     * 
     * @type {TvSeasonWatchProviders200ResponseResultsFI}
     * @memberof TvSeasonWatchProviders200ResponseResults
     */
    fI?: TvSeasonWatchProviders200ResponseResultsFI;
    /**
     * 
     * @type {TvSeasonWatchProviders200ResponseResultsFR}
     * @memberof TvSeasonWatchProviders200ResponseResults
     */
    fR?: TvSeasonWatchProviders200ResponseResultsFR;
    /**
     * 
     * @type {TvSeasonWatchProviders200ResponseResultsGB}
     * @memberof TvSeasonWatchProviders200ResponseResults
     */
    gB?: TvSeasonWatchProviders200ResponseResultsGB;
    /**
     * 
     * @type {TvSeasonWatchProviders200ResponseResultsGF}
     * @memberof TvSeasonWatchProviders200ResponseResults
     */
    gF?: TvSeasonWatchProviders200ResponseResultsGF;
    /**
     * 
     * @type {TvSeasonWatchProviders200ResponseResultsGH}
     * @memberof TvSeasonWatchProviders200ResponseResults
     */
    gH?: TvSeasonWatchProviders200ResponseResultsGH;
    /**
     * 
     * @type {TvSeasonWatchProviders200ResponseResultsGQ}
     * @memberof TvSeasonWatchProviders200ResponseResults
     */
    gQ?: TvSeasonWatchProviders200ResponseResultsGQ;
    /**
     * 
     * @type {TvSeasonWatchProviders200ResponseResultsGT}
     * @memberof TvSeasonWatchProviders200ResponseResults
     */
    gT?: TvSeasonWatchProviders200ResponseResultsGT;
    /**
     * 
     * @type {TvSeasonWatchProviders200ResponseResultsHK}
     * @memberof TvSeasonWatchProviders200ResponseResults
     */
    hK?: TvSeasonWatchProviders200ResponseResultsHK;
    /**
     * 
     * @type {TvSeasonWatchProviders200ResponseResultsHN}
     * @memberof TvSeasonWatchProviders200ResponseResults
     */
    hN?: TvSeasonWatchProviders200ResponseResultsHN;
    /**
     * 
     * @type {TvSeasonWatchProviders200ResponseResultsHR}
     * @memberof TvSeasonWatchProviders200ResponseResults
     */
    hR?: TvSeasonWatchProviders200ResponseResultsHR;
    /**
     * 
     * @type {TvSeasonWatchProviders200ResponseResultsHU}
     * @memberof TvSeasonWatchProviders200ResponseResults
     */
    hU?: TvSeasonWatchProviders200ResponseResultsHU;
    /**
     * 
     * @type {TvSeasonWatchProviders200ResponseResultsID}
     * @memberof TvSeasonWatchProviders200ResponseResults
     */
    iD?: TvSeasonWatchProviders200ResponseResultsID;
    /**
     * 
     * @type {TvSeasonWatchProviders200ResponseResultsIE}
     * @memberof TvSeasonWatchProviders200ResponseResults
     */
    iE?: TvSeasonWatchProviders200ResponseResultsIE;
    /**
     * 
     * @type {TvSeasonWatchProviders200ResponseResultsIL}
     * @memberof TvSeasonWatchProviders200ResponseResults
     */
    iL?: TvSeasonWatchProviders200ResponseResultsIL;
    /**
     * 
     * @type {TvSeasonWatchProviders200ResponseResultsIQ}
     * @memberof TvSeasonWatchProviders200ResponseResults
     */
    iQ?: TvSeasonWatchProviders200ResponseResultsIQ;
    /**
     * 
     * @type {TvSeasonWatchProviders200ResponseResultsIT}
     * @memberof TvSeasonWatchProviders200ResponseResults
     */
    iT?: TvSeasonWatchProviders200ResponseResultsIT;
    /**
     * 
     * @type {TvSeasonWatchProviders200ResponseResultsJM}
     * @memberof TvSeasonWatchProviders200ResponseResults
     */
    jM?: TvSeasonWatchProviders200ResponseResultsJM;
    /**
     * 
     * @type {TvSeasonWatchProviders200ResponseResultsJP}
     * @memberof TvSeasonWatchProviders200ResponseResults
     */
    jP?: TvSeasonWatchProviders200ResponseResultsJP;
    /**
     * 
     * @type {TvSeasonWatchProviders200ResponseResultsKE}
     * @memberof TvSeasonWatchProviders200ResponseResults
     */
    kE?: TvSeasonWatchProviders200ResponseResultsKE;
    /**
     * 
     * @type {TvSeasonWatchProviders200ResponseResultsKR}
     * @memberof TvSeasonWatchProviders200ResponseResults
     */
    kR?: TvSeasonWatchProviders200ResponseResultsKR;
    /**
     * 
     * @type {TvSeasonWatchProviders200ResponseResultsLB}
     * @memberof TvSeasonWatchProviders200ResponseResults
     */
    lB?: TvSeasonWatchProviders200ResponseResultsLB;
    /**
     * 
     * @type {TvSeasonWatchProviders200ResponseResultsLY}
     * @memberof TvSeasonWatchProviders200ResponseResults
     */
    lY?: TvSeasonWatchProviders200ResponseResultsLY;
    /**
     * 
     * @type {TvSeasonWatchProviders200ResponseResultsMD}
     * @memberof TvSeasonWatchProviders200ResponseResults
     */
    mD?: TvSeasonWatchProviders200ResponseResultsMD;
    /**
     * 
     * @type {TvSeasonWatchProviders200ResponseResultsMK}
     * @memberof TvSeasonWatchProviders200ResponseResults
     */
    mK?: TvSeasonWatchProviders200ResponseResultsMK;
    /**
     * 
     * @type {TvSeasonWatchProviders200ResponseResultsMU}
     * @memberof TvSeasonWatchProviders200ResponseResults
     */
    mU?: TvSeasonWatchProviders200ResponseResultsMU;
    /**
     * 
     * @type {TvSeasonWatchProviders200ResponseResultsMX}
     * @memberof TvSeasonWatchProviders200ResponseResults
     */
    mX?: TvSeasonWatchProviders200ResponseResultsMX;
    /**
     * 
     * @type {TvSeasonWatchProviders200ResponseResultsMY}
     * @memberof TvSeasonWatchProviders200ResponseResults
     */
    mY?: TvSeasonWatchProviders200ResponseResultsMY;
    /**
     * 
     * @type {TvSeasonWatchProviders200ResponseResultsMZ}
     * @memberof TvSeasonWatchProviders200ResponseResults
     */
    mZ?: TvSeasonWatchProviders200ResponseResultsMZ;
    /**
     * 
     * @type {TvSeasonWatchProviders200ResponseResultsNE}
     * @memberof TvSeasonWatchProviders200ResponseResults
     */
    nE?: TvSeasonWatchProviders200ResponseResultsNE;
    /**
     * 
     * @type {TvSeasonWatchProviders200ResponseResultsNG}
     * @memberof TvSeasonWatchProviders200ResponseResults
     */
    nG?: TvSeasonWatchProviders200ResponseResultsNG;
    /**
     * 
     * @type {TvSeasonWatchProviders200ResponseResultsNL}
     * @memberof TvSeasonWatchProviders200ResponseResults
     */
    nL?: TvSeasonWatchProviders200ResponseResultsNL;
    /**
     * 
     * @type {TvSeasonWatchProviders200ResponseResultsNO}
     * @memberof TvSeasonWatchProviders200ResponseResults
     */
    nO?: TvSeasonWatchProviders200ResponseResultsNO;
    /**
     * 
     * @type {TvSeasonWatchProviders200ResponseResultsNZ}
     * @memberof TvSeasonWatchProviders200ResponseResults
     */
    nZ?: TvSeasonWatchProviders200ResponseResultsNZ;
    /**
     * 
     * @type {TvSeasonWatchProviders200ResponseResultsPA}
     * @memberof TvSeasonWatchProviders200ResponseResults
     */
    pA?: TvSeasonWatchProviders200ResponseResultsPA;
    /**
     * 
     * @type {TvSeasonWatchProviders200ResponseResultsPE}
     * @memberof TvSeasonWatchProviders200ResponseResults
     */
    pE?: TvSeasonWatchProviders200ResponseResultsPE;
    /**
     * 
     * @type {TvSeasonWatchProviders200ResponseResultsPH}
     * @memberof TvSeasonWatchProviders200ResponseResults
     */
    pH?: TvSeasonWatchProviders200ResponseResultsPH;
    /**
     * 
     * @type {TvSeasonWatchProviders200ResponseResultsPL}
     * @memberof TvSeasonWatchProviders200ResponseResults
     */
    pL?: TvSeasonWatchProviders200ResponseResultsPL;
    /**
     * 
     * @type {TvSeasonWatchProviders200ResponseResultsPS}
     * @memberof TvSeasonWatchProviders200ResponseResults
     */
    pS?: TvSeasonWatchProviders200ResponseResultsPS;
    /**
     * 
     * @type {TvSeasonWatchProviders200ResponseResultsPT}
     * @memberof TvSeasonWatchProviders200ResponseResults
     */
    pT?: TvSeasonWatchProviders200ResponseResultsPT;
    /**
     * 
     * @type {TvSeasonWatchProviders200ResponseResultsPY}
     * @memberof TvSeasonWatchProviders200ResponseResults
     */
    pY?: TvSeasonWatchProviders200ResponseResultsPY;
    /**
     * 
     * @type {TvSeasonWatchProviders200ResponseResultsRO}
     * @memberof TvSeasonWatchProviders200ResponseResults
     */
    rO?: TvSeasonWatchProviders200ResponseResultsRO;
    /**
     * 
     * @type {TvSeasonWatchProviders200ResponseResultsRS}
     * @memberof TvSeasonWatchProviders200ResponseResults
     */
    rS?: TvSeasonWatchProviders200ResponseResultsRS;
    /**
     * 
     * @type {TvSeasonWatchProviders200ResponseResultsRU}
     * @memberof TvSeasonWatchProviders200ResponseResults
     */
    rU?: TvSeasonWatchProviders200ResponseResultsRU;
    /**
     * 
     * @type {TvSeasonWatchProviders200ResponseResultsSA}
     * @memberof TvSeasonWatchProviders200ResponseResults
     */
    sA?: TvSeasonWatchProviders200ResponseResultsSA;
    /**
     * 
     * @type {TvSeasonWatchProviders200ResponseResultsSC}
     * @memberof TvSeasonWatchProviders200ResponseResults
     */
    sC?: TvSeasonWatchProviders200ResponseResultsSC;
    /**
     * 
     * @type {TvSeasonWatchProviders200ResponseResultsSE}
     * @memberof TvSeasonWatchProviders200ResponseResults
     */
    sE?: TvSeasonWatchProviders200ResponseResultsSE;
    /**
     * 
     * @type {TvSeasonWatchProviders200ResponseResultsSG}
     * @memberof TvSeasonWatchProviders200ResponseResults
     */
    sG?: TvSeasonWatchProviders200ResponseResultsSG;
    /**
     * 
     * @type {TvSeasonWatchProviders200ResponseResultsSI}
     * @memberof TvSeasonWatchProviders200ResponseResults
     */
    sI?: TvSeasonWatchProviders200ResponseResultsSI;
    /**
     * 
     * @type {TvSeasonWatchProviders200ResponseResultsSK}
     * @memberof TvSeasonWatchProviders200ResponseResults
     */
    sK?: TvSeasonWatchProviders200ResponseResultsSK;
    /**
     * 
     * @type {TvSeasonWatchProviders200ResponseResultsSN}
     * @memberof TvSeasonWatchProviders200ResponseResults
     */
    sN?: TvSeasonWatchProviders200ResponseResultsSN;
    /**
     * 
     * @type {TvSeasonWatchProviders200ResponseResultsSV}
     * @memberof TvSeasonWatchProviders200ResponseResults
     */
    sV?: TvSeasonWatchProviders200ResponseResultsSV;
    /**
     * 
     * @type {TvSeasonWatchProviders200ResponseResultsTH}
     * @memberof TvSeasonWatchProviders200ResponseResults
     */
    tH?: TvSeasonWatchProviders200ResponseResultsTH;
    /**
     * 
     * @type {TvSeasonWatchProviders200ResponseResultsTR}
     * @memberof TvSeasonWatchProviders200ResponseResults
     */
    tR?: TvSeasonWatchProviders200ResponseResultsTR;
    /**
     * 
     * @type {TvSeasonWatchProviders200ResponseResultsTT}
     * @memberof TvSeasonWatchProviders200ResponseResults
     */
    tT?: TvSeasonWatchProviders200ResponseResultsTT;
    /**
     * 
     * @type {TvSeasonWatchProviders200ResponseResultsTW}
     * @memberof TvSeasonWatchProviders200ResponseResults
     */
    tW?: TvSeasonWatchProviders200ResponseResultsTW;
    /**
     * 
     * @type {TvSeasonWatchProviders200ResponseResultsTZ}
     * @memberof TvSeasonWatchProviders200ResponseResults
     */
    tZ?: TvSeasonWatchProviders200ResponseResultsTZ;
    /**
     * 
     * @type {TvSeasonWatchProviders200ResponseResultsUG}
     * @memberof TvSeasonWatchProviders200ResponseResults
     */
    uG?: TvSeasonWatchProviders200ResponseResultsUG;
    /**
     * 
     * @type {TvSeasonWatchProviders200ResponseResultsUS}
     * @memberof TvSeasonWatchProviders200ResponseResults
     */
    uS?: TvSeasonWatchProviders200ResponseResultsUS;
    /**
     * 
     * @type {TvSeasonWatchProviders200ResponseResultsUY}
     * @memberof TvSeasonWatchProviders200ResponseResults
     */
    uY?: TvSeasonWatchProviders200ResponseResultsUY;
    /**
     * 
     * @type {TvSeasonWatchProviders200ResponseResultsVE}
     * @memberof TvSeasonWatchProviders200ResponseResults
     */
    vE?: TvSeasonWatchProviders200ResponseResultsVE;
    /**
     * 
     * @type {TvSeasonWatchProviders200ResponseResultsZA}
     * @memberof TvSeasonWatchProviders200ResponseResults
     */
    zA?: TvSeasonWatchProviders200ResponseResultsZA;
    /**
     * 
     * @type {TvSeasonWatchProviders200ResponseResultsZM}
     * @memberof TvSeasonWatchProviders200ResponseResults
     */
    zM?: TvSeasonWatchProviders200ResponseResultsZM;
}

/**
 * Check if a given object implements the TvSeasonWatchProviders200ResponseResults interface.
 */
export function instanceOfTvSeasonWatchProviders200ResponseResults(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function TvSeasonWatchProviders200ResponseResultsFromJSON(json: any): TvSeasonWatchProviders200ResponseResults {
    return TvSeasonWatchProviders200ResponseResultsFromJSONTyped(json, false);
}

export function TvSeasonWatchProviders200ResponseResultsFromJSONTyped(json: any, ignoreDiscriminator: boolean): TvSeasonWatchProviders200ResponseResults {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'aE': !exists(json, 'AE') ? undefined : TvSeasonWatchProviders200ResponseResultsAEFromJSON(json['AE']),
        'aR': !exists(json, 'AR') ? undefined : TvSeasonWatchProviders200ResponseResultsARFromJSON(json['AR']),
        'aT': !exists(json, 'AT') ? undefined : TvSeasonWatchProviders200ResponseResultsATFromJSON(json['AT']),
        'aU': !exists(json, 'AU') ? undefined : TvSeasonWatchProviders200ResponseResultsAUFromJSON(json['AU']),
        'bA': !exists(json, 'BA') ? undefined : TvSeasonWatchProviders200ResponseResultsBAFromJSON(json['BA']),
        'bB': !exists(json, 'BB') ? undefined : TvSeasonWatchProviders200ResponseResultsBBFromJSON(json['BB']),
        'bE': !exists(json, 'BE') ? undefined : TvSeasonWatchProviders200ResponseResultsBEFromJSON(json['BE']),
        'bG': !exists(json, 'BG') ? undefined : TvSeasonWatchProviders200ResponseResultsBGFromJSON(json['BG']),
        'bO': !exists(json, 'BO') ? undefined : TvSeasonWatchProviders200ResponseResultsBOFromJSON(json['BO']),
        'bR': !exists(json, 'BR') ? undefined : TvSeasonWatchProviders200ResponseResultsBRFromJSON(json['BR']),
        'bS': !exists(json, 'BS') ? undefined : TvSeasonWatchProviders200ResponseResultsBSFromJSON(json['BS']),
        'cA': !exists(json, 'CA') ? undefined : TvSeasonWatchProviders200ResponseResultsCAFromJSON(json['CA']),
        'cH': !exists(json, 'CH') ? undefined : TvSeasonWatchProviders200ResponseResultsCHFromJSON(json['CH']),
        'cI': !exists(json, 'CI') ? undefined : TvSeasonWatchProviders200ResponseResultsCIFromJSON(json['CI']),
        'cL': !exists(json, 'CL') ? undefined : TvSeasonWatchProviders200ResponseResultsCLFromJSON(json['CL']),
        'cO': !exists(json, 'CO') ? undefined : TvSeasonWatchProviders200ResponseResultsCOFromJSON(json['CO']),
        'cR': !exists(json, 'CR') ? undefined : TvSeasonWatchProviders200ResponseResultsCRFromJSON(json['CR']),
        'cZ': !exists(json, 'CZ') ? undefined : TvSeasonWatchProviders200ResponseResultsCZFromJSON(json['CZ']),
        'dE': !exists(json, 'DE') ? undefined : TvSeasonWatchProviders200ResponseResultsDEFromJSON(json['DE']),
        'dK': !exists(json, 'DK') ? undefined : TvSeasonWatchProviders200ResponseResultsDKFromJSON(json['DK']),
        'dO': !exists(json, 'DO') ? undefined : TvSeasonWatchProviders200ResponseResultsDOFromJSON(json['DO']),
        'dZ': !exists(json, 'DZ') ? undefined : TvSeasonWatchProviders200ResponseResultsDZFromJSON(json['DZ']),
        'eC': !exists(json, 'EC') ? undefined : TvSeasonWatchProviders200ResponseResultsECFromJSON(json['EC']),
        'eG': !exists(json, 'EG') ? undefined : TvSeasonWatchProviders200ResponseResultsEGFromJSON(json['EG']),
        'eS': !exists(json, 'ES') ? undefined : TvSeasonWatchProviders200ResponseResultsESFromJSON(json['ES']),
        'fI': !exists(json, 'FI') ? undefined : TvSeasonWatchProviders200ResponseResultsFIFromJSON(json['FI']),
        'fR': !exists(json, 'FR') ? undefined : TvSeasonWatchProviders200ResponseResultsFRFromJSON(json['FR']),
        'gB': !exists(json, 'GB') ? undefined : TvSeasonWatchProviders200ResponseResultsGBFromJSON(json['GB']),
        'gF': !exists(json, 'GF') ? undefined : TvSeasonWatchProviders200ResponseResultsGFFromJSON(json['GF']),
        'gH': !exists(json, 'GH') ? undefined : TvSeasonWatchProviders200ResponseResultsGHFromJSON(json['GH']),
        'gQ': !exists(json, 'GQ') ? undefined : TvSeasonWatchProviders200ResponseResultsGQFromJSON(json['GQ']),
        'gT': !exists(json, 'GT') ? undefined : TvSeasonWatchProviders200ResponseResultsGTFromJSON(json['GT']),
        'hK': !exists(json, 'HK') ? undefined : TvSeasonWatchProviders200ResponseResultsHKFromJSON(json['HK']),
        'hN': !exists(json, 'HN') ? undefined : TvSeasonWatchProviders200ResponseResultsHNFromJSON(json['HN']),
        'hR': !exists(json, 'HR') ? undefined : TvSeasonWatchProviders200ResponseResultsHRFromJSON(json['HR']),
        'hU': !exists(json, 'HU') ? undefined : TvSeasonWatchProviders200ResponseResultsHUFromJSON(json['HU']),
        'iD': !exists(json, 'ID') ? undefined : TvSeasonWatchProviders200ResponseResultsIDFromJSON(json['ID']),
        'iE': !exists(json, 'IE') ? undefined : TvSeasonWatchProviders200ResponseResultsIEFromJSON(json['IE']),
        'iL': !exists(json, 'IL') ? undefined : TvSeasonWatchProviders200ResponseResultsILFromJSON(json['IL']),
        'iQ': !exists(json, 'IQ') ? undefined : TvSeasonWatchProviders200ResponseResultsIQFromJSON(json['IQ']),
        'iT': !exists(json, 'IT') ? undefined : TvSeasonWatchProviders200ResponseResultsITFromJSON(json['IT']),
        'jM': !exists(json, 'JM') ? undefined : TvSeasonWatchProviders200ResponseResultsJMFromJSON(json['JM']),
        'jP': !exists(json, 'JP') ? undefined : TvSeasonWatchProviders200ResponseResultsJPFromJSON(json['JP']),
        'kE': !exists(json, 'KE') ? undefined : TvSeasonWatchProviders200ResponseResultsKEFromJSON(json['KE']),
        'kR': !exists(json, 'KR') ? undefined : TvSeasonWatchProviders200ResponseResultsKRFromJSON(json['KR']),
        'lB': !exists(json, 'LB') ? undefined : TvSeasonWatchProviders200ResponseResultsLBFromJSON(json['LB']),
        'lY': !exists(json, 'LY') ? undefined : TvSeasonWatchProviders200ResponseResultsLYFromJSON(json['LY']),
        'mD': !exists(json, 'MD') ? undefined : TvSeasonWatchProviders200ResponseResultsMDFromJSON(json['MD']),
        'mK': !exists(json, 'MK') ? undefined : TvSeasonWatchProviders200ResponseResultsMKFromJSON(json['MK']),
        'mU': !exists(json, 'MU') ? undefined : TvSeasonWatchProviders200ResponseResultsMUFromJSON(json['MU']),
        'mX': !exists(json, 'MX') ? undefined : TvSeasonWatchProviders200ResponseResultsMXFromJSON(json['MX']),
        'mY': !exists(json, 'MY') ? undefined : TvSeasonWatchProviders200ResponseResultsMYFromJSON(json['MY']),
        'mZ': !exists(json, 'MZ') ? undefined : TvSeasonWatchProviders200ResponseResultsMZFromJSON(json['MZ']),
        'nE': !exists(json, 'NE') ? undefined : TvSeasonWatchProviders200ResponseResultsNEFromJSON(json['NE']),
        'nG': !exists(json, 'NG') ? undefined : TvSeasonWatchProviders200ResponseResultsNGFromJSON(json['NG']),
        'nL': !exists(json, 'NL') ? undefined : TvSeasonWatchProviders200ResponseResultsNLFromJSON(json['NL']),
        'nO': !exists(json, 'NO') ? undefined : TvSeasonWatchProviders200ResponseResultsNOFromJSON(json['NO']),
        'nZ': !exists(json, 'NZ') ? undefined : TvSeasonWatchProviders200ResponseResultsNZFromJSON(json['NZ']),
        'pA': !exists(json, 'PA') ? undefined : TvSeasonWatchProviders200ResponseResultsPAFromJSON(json['PA']),
        'pE': !exists(json, 'PE') ? undefined : TvSeasonWatchProviders200ResponseResultsPEFromJSON(json['PE']),
        'pH': !exists(json, 'PH') ? undefined : TvSeasonWatchProviders200ResponseResultsPHFromJSON(json['PH']),
        'pL': !exists(json, 'PL') ? undefined : TvSeasonWatchProviders200ResponseResultsPLFromJSON(json['PL']),
        'pS': !exists(json, 'PS') ? undefined : TvSeasonWatchProviders200ResponseResultsPSFromJSON(json['PS']),
        'pT': !exists(json, 'PT') ? undefined : TvSeasonWatchProviders200ResponseResultsPTFromJSON(json['PT']),
        'pY': !exists(json, 'PY') ? undefined : TvSeasonWatchProviders200ResponseResultsPYFromJSON(json['PY']),
        'rO': !exists(json, 'RO') ? undefined : TvSeasonWatchProviders200ResponseResultsROFromJSON(json['RO']),
        'rS': !exists(json, 'RS') ? undefined : TvSeasonWatchProviders200ResponseResultsRSFromJSON(json['RS']),
        'rU': !exists(json, 'RU') ? undefined : TvSeasonWatchProviders200ResponseResultsRUFromJSON(json['RU']),
        'sA': !exists(json, 'SA') ? undefined : TvSeasonWatchProviders200ResponseResultsSAFromJSON(json['SA']),
        'sC': !exists(json, 'SC') ? undefined : TvSeasonWatchProviders200ResponseResultsSCFromJSON(json['SC']),
        'sE': !exists(json, 'SE') ? undefined : TvSeasonWatchProviders200ResponseResultsSEFromJSON(json['SE']),
        'sG': !exists(json, 'SG') ? undefined : TvSeasonWatchProviders200ResponseResultsSGFromJSON(json['SG']),
        'sI': !exists(json, 'SI') ? undefined : TvSeasonWatchProviders200ResponseResultsSIFromJSON(json['SI']),
        'sK': !exists(json, 'SK') ? undefined : TvSeasonWatchProviders200ResponseResultsSKFromJSON(json['SK']),
        'sN': !exists(json, 'SN') ? undefined : TvSeasonWatchProviders200ResponseResultsSNFromJSON(json['SN']),
        'sV': !exists(json, 'SV') ? undefined : TvSeasonWatchProviders200ResponseResultsSVFromJSON(json['SV']),
        'tH': !exists(json, 'TH') ? undefined : TvSeasonWatchProviders200ResponseResultsTHFromJSON(json['TH']),
        'tR': !exists(json, 'TR') ? undefined : TvSeasonWatchProviders200ResponseResultsTRFromJSON(json['TR']),
        'tT': !exists(json, 'TT') ? undefined : TvSeasonWatchProviders200ResponseResultsTTFromJSON(json['TT']),
        'tW': !exists(json, 'TW') ? undefined : TvSeasonWatchProviders200ResponseResultsTWFromJSON(json['TW']),
        'tZ': !exists(json, 'TZ') ? undefined : TvSeasonWatchProviders200ResponseResultsTZFromJSON(json['TZ']),
        'uG': !exists(json, 'UG') ? undefined : TvSeasonWatchProviders200ResponseResultsUGFromJSON(json['UG']),
        'uS': !exists(json, 'US') ? undefined : TvSeasonWatchProviders200ResponseResultsUSFromJSON(json['US']),
        'uY': !exists(json, 'UY') ? undefined : TvSeasonWatchProviders200ResponseResultsUYFromJSON(json['UY']),
        'vE': !exists(json, 'VE') ? undefined : TvSeasonWatchProviders200ResponseResultsVEFromJSON(json['VE']),
        'zA': !exists(json, 'ZA') ? undefined : TvSeasonWatchProviders200ResponseResultsZAFromJSON(json['ZA']),
        'zM': !exists(json, 'ZM') ? undefined : TvSeasonWatchProviders200ResponseResultsZMFromJSON(json['ZM']),
    };
}

export function TvSeasonWatchProviders200ResponseResultsToJSON(value?: TvSeasonWatchProviders200ResponseResults | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'AE': TvSeasonWatchProviders200ResponseResultsAEToJSON(value.aE),
        'AR': TvSeasonWatchProviders200ResponseResultsARToJSON(value.aR),
        'AT': TvSeasonWatchProviders200ResponseResultsATToJSON(value.aT),
        'AU': TvSeasonWatchProviders200ResponseResultsAUToJSON(value.aU),
        'BA': TvSeasonWatchProviders200ResponseResultsBAToJSON(value.bA),
        'BB': TvSeasonWatchProviders200ResponseResultsBBToJSON(value.bB),
        'BE': TvSeasonWatchProviders200ResponseResultsBEToJSON(value.bE),
        'BG': TvSeasonWatchProviders200ResponseResultsBGToJSON(value.bG),
        'BO': TvSeasonWatchProviders200ResponseResultsBOToJSON(value.bO),
        'BR': TvSeasonWatchProviders200ResponseResultsBRToJSON(value.bR),
        'BS': TvSeasonWatchProviders200ResponseResultsBSToJSON(value.bS),
        'CA': TvSeasonWatchProviders200ResponseResultsCAToJSON(value.cA),
        'CH': TvSeasonWatchProviders200ResponseResultsCHToJSON(value.cH),
        'CI': TvSeasonWatchProviders200ResponseResultsCIToJSON(value.cI),
        'CL': TvSeasonWatchProviders200ResponseResultsCLToJSON(value.cL),
        'CO': TvSeasonWatchProviders200ResponseResultsCOToJSON(value.cO),
        'CR': TvSeasonWatchProviders200ResponseResultsCRToJSON(value.cR),
        'CZ': TvSeasonWatchProviders200ResponseResultsCZToJSON(value.cZ),
        'DE': TvSeasonWatchProviders200ResponseResultsDEToJSON(value.dE),
        'DK': TvSeasonWatchProviders200ResponseResultsDKToJSON(value.dK),
        'DO': TvSeasonWatchProviders200ResponseResultsDOToJSON(value.dO),
        'DZ': TvSeasonWatchProviders200ResponseResultsDZToJSON(value.dZ),
        'EC': TvSeasonWatchProviders200ResponseResultsECToJSON(value.eC),
        'EG': TvSeasonWatchProviders200ResponseResultsEGToJSON(value.eG),
        'ES': TvSeasonWatchProviders200ResponseResultsESToJSON(value.eS),
        'FI': TvSeasonWatchProviders200ResponseResultsFIToJSON(value.fI),
        'FR': TvSeasonWatchProviders200ResponseResultsFRToJSON(value.fR),
        'GB': TvSeasonWatchProviders200ResponseResultsGBToJSON(value.gB),
        'GF': TvSeasonWatchProviders200ResponseResultsGFToJSON(value.gF),
        'GH': TvSeasonWatchProviders200ResponseResultsGHToJSON(value.gH),
        'GQ': TvSeasonWatchProviders200ResponseResultsGQToJSON(value.gQ),
        'GT': TvSeasonWatchProviders200ResponseResultsGTToJSON(value.gT),
        'HK': TvSeasonWatchProviders200ResponseResultsHKToJSON(value.hK),
        'HN': TvSeasonWatchProviders200ResponseResultsHNToJSON(value.hN),
        'HR': TvSeasonWatchProviders200ResponseResultsHRToJSON(value.hR),
        'HU': TvSeasonWatchProviders200ResponseResultsHUToJSON(value.hU),
        'ID': TvSeasonWatchProviders200ResponseResultsIDToJSON(value.iD),
        'IE': TvSeasonWatchProviders200ResponseResultsIEToJSON(value.iE),
        'IL': TvSeasonWatchProviders200ResponseResultsILToJSON(value.iL),
        'IQ': TvSeasonWatchProviders200ResponseResultsIQToJSON(value.iQ),
        'IT': TvSeasonWatchProviders200ResponseResultsITToJSON(value.iT),
        'JM': TvSeasonWatchProviders200ResponseResultsJMToJSON(value.jM),
        'JP': TvSeasonWatchProviders200ResponseResultsJPToJSON(value.jP),
        'KE': TvSeasonWatchProviders200ResponseResultsKEToJSON(value.kE),
        'KR': TvSeasonWatchProviders200ResponseResultsKRToJSON(value.kR),
        'LB': TvSeasonWatchProviders200ResponseResultsLBToJSON(value.lB),
        'LY': TvSeasonWatchProviders200ResponseResultsLYToJSON(value.lY),
        'MD': TvSeasonWatchProviders200ResponseResultsMDToJSON(value.mD),
        'MK': TvSeasonWatchProviders200ResponseResultsMKToJSON(value.mK),
        'MU': TvSeasonWatchProviders200ResponseResultsMUToJSON(value.mU),
        'MX': TvSeasonWatchProviders200ResponseResultsMXToJSON(value.mX),
        'MY': TvSeasonWatchProviders200ResponseResultsMYToJSON(value.mY),
        'MZ': TvSeasonWatchProviders200ResponseResultsMZToJSON(value.mZ),
        'NE': TvSeasonWatchProviders200ResponseResultsNEToJSON(value.nE),
        'NG': TvSeasonWatchProviders200ResponseResultsNGToJSON(value.nG),
        'NL': TvSeasonWatchProviders200ResponseResultsNLToJSON(value.nL),
        'NO': TvSeasonWatchProviders200ResponseResultsNOToJSON(value.nO),
        'NZ': TvSeasonWatchProviders200ResponseResultsNZToJSON(value.nZ),
        'PA': TvSeasonWatchProviders200ResponseResultsPAToJSON(value.pA),
        'PE': TvSeasonWatchProviders200ResponseResultsPEToJSON(value.pE),
        'PH': TvSeasonWatchProviders200ResponseResultsPHToJSON(value.pH),
        'PL': TvSeasonWatchProviders200ResponseResultsPLToJSON(value.pL),
        'PS': TvSeasonWatchProviders200ResponseResultsPSToJSON(value.pS),
        'PT': TvSeasonWatchProviders200ResponseResultsPTToJSON(value.pT),
        'PY': TvSeasonWatchProviders200ResponseResultsPYToJSON(value.pY),
        'RO': TvSeasonWatchProviders200ResponseResultsROToJSON(value.rO),
        'RS': TvSeasonWatchProviders200ResponseResultsRSToJSON(value.rS),
        'RU': TvSeasonWatchProviders200ResponseResultsRUToJSON(value.rU),
        'SA': TvSeasonWatchProviders200ResponseResultsSAToJSON(value.sA),
        'SC': TvSeasonWatchProviders200ResponseResultsSCToJSON(value.sC),
        'SE': TvSeasonWatchProviders200ResponseResultsSEToJSON(value.sE),
        'SG': TvSeasonWatchProviders200ResponseResultsSGToJSON(value.sG),
        'SI': TvSeasonWatchProviders200ResponseResultsSIToJSON(value.sI),
        'SK': TvSeasonWatchProviders200ResponseResultsSKToJSON(value.sK),
        'SN': TvSeasonWatchProviders200ResponseResultsSNToJSON(value.sN),
        'SV': TvSeasonWatchProviders200ResponseResultsSVToJSON(value.sV),
        'TH': TvSeasonWatchProviders200ResponseResultsTHToJSON(value.tH),
        'TR': TvSeasonWatchProviders200ResponseResultsTRToJSON(value.tR),
        'TT': TvSeasonWatchProviders200ResponseResultsTTToJSON(value.tT),
        'TW': TvSeasonWatchProviders200ResponseResultsTWToJSON(value.tW),
        'TZ': TvSeasonWatchProviders200ResponseResultsTZToJSON(value.tZ),
        'UG': TvSeasonWatchProviders200ResponseResultsUGToJSON(value.uG),
        'US': TvSeasonWatchProviders200ResponseResultsUSToJSON(value.uS),
        'UY': TvSeasonWatchProviders200ResponseResultsUYToJSON(value.uY),
        'VE': TvSeasonWatchProviders200ResponseResultsVEToJSON(value.vE),
        'ZA': TvSeasonWatchProviders200ResponseResultsZAToJSON(value.zA),
        'ZM': TvSeasonWatchProviders200ResponseResultsZMToJSON(value.zM),
    };
}

