/* tslint:disable */
/* eslint-disable */
/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TvSeriesDetails200ResponseLastEpisodeToAir
 */
export interface TvSeriesDetails200ResponseLastEpisodeToAir {
    /**
     * 
     * @type {any}
     * @memberof TvSeriesDetails200ResponseLastEpisodeToAir
     */
    id?: any | null;
    /**
     * 
     * @type {any}
     * @memberof TvSeriesDetails200ResponseLastEpisodeToAir
     */
    name?: any | null;
    /**
     * 
     * @type {any}
     * @memberof TvSeriesDetails200ResponseLastEpisodeToAir
     */
    overview?: any | null;
    /**
     * 
     * @type {any}
     * @memberof TvSeriesDetails200ResponseLastEpisodeToAir
     */
    voteAverage?: any | null;
    /**
     * 
     * @type {any}
     * @memberof TvSeriesDetails200ResponseLastEpisodeToAir
     */
    voteCount?: any | null;
    /**
     * 
     * @type {any}
     * @memberof TvSeriesDetails200ResponseLastEpisodeToAir
     */
    airDate?: any | null;
    /**
     * 
     * @type {any}
     * @memberof TvSeriesDetails200ResponseLastEpisodeToAir
     */
    episodeNumber?: any | null;
    /**
     * 
     * @type {any}
     * @memberof TvSeriesDetails200ResponseLastEpisodeToAir
     */
    productionCode?: any | null;
    /**
     * 
     * @type {any}
     * @memberof TvSeriesDetails200ResponseLastEpisodeToAir
     */
    runtime?: any | null;
    /**
     * 
     * @type {any}
     * @memberof TvSeriesDetails200ResponseLastEpisodeToAir
     */
    seasonNumber?: any | null;
    /**
     * 
     * @type {any}
     * @memberof TvSeriesDetails200ResponseLastEpisodeToAir
     */
    showId?: any | null;
    /**
     * 
     * @type {any}
     * @memberof TvSeriesDetails200ResponseLastEpisodeToAir
     */
    stillPath?: any | null;
}

/**
 * Check if a given object implements the TvSeriesDetails200ResponseLastEpisodeToAir interface.
 */
export function instanceOfTvSeriesDetails200ResponseLastEpisodeToAir(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function TvSeriesDetails200ResponseLastEpisodeToAirFromJSON(json: any): TvSeriesDetails200ResponseLastEpisodeToAir {
    return TvSeriesDetails200ResponseLastEpisodeToAirFromJSONTyped(json, false);
}

export function TvSeriesDetails200ResponseLastEpisodeToAirFromJSONTyped(json: any, ignoreDiscriminator: boolean): TvSeriesDetails200ResponseLastEpisodeToAir {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'overview': !exists(json, 'overview') ? undefined : json['overview'],
        'voteAverage': !exists(json, 'vote_average') ? undefined : json['vote_average'],
        'voteCount': !exists(json, 'vote_count') ? undefined : json['vote_count'],
        'airDate': !exists(json, 'air_date') ? undefined : json['air_date'],
        'episodeNumber': !exists(json, 'episode_number') ? undefined : json['episode_number'],
        'productionCode': !exists(json, 'production_code') ? undefined : json['production_code'],
        'runtime': !exists(json, 'runtime') ? undefined : json['runtime'],
        'seasonNumber': !exists(json, 'season_number') ? undefined : json['season_number'],
        'showId': !exists(json, 'show_id') ? undefined : json['show_id'],
        'stillPath': !exists(json, 'still_path') ? undefined : json['still_path'],
    };
}

export function TvSeriesDetails200ResponseLastEpisodeToAirToJSON(value?: TvSeriesDetails200ResponseLastEpisodeToAir | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'overview': value.overview,
        'vote_average': value.voteAverage,
        'vote_count': value.voteCount,
        'air_date': value.airDate,
        'episode_number': value.episodeNumber,
        'production_code': value.productionCode,
        'runtime': value.runtime,
        'season_number': value.seasonNumber,
        'show_id': value.showId,
        'still_path': value.stillPath,
    };
}

