/* tslint:disable */
/* eslint-disable */
/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TvSeriesKeywords200Response
 */
export interface TvSeriesKeywords200Response {
    /**
     * 
     * @type {any}
     * @memberof TvSeriesKeywords200Response
     */
    id?: any | null;
    /**
     * 
     * @type {any}
     * @memberof TvSeriesKeywords200Response
     */
    results?: any | null;
}

/**
 * Check if a given object implements the TvSeriesKeywords200Response interface.
 */
export function instanceOfTvSeriesKeywords200Response(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function TvSeriesKeywords200ResponseFromJSON(json: any): TvSeriesKeywords200Response {
    return TvSeriesKeywords200ResponseFromJSONTyped(json, false);
}

export function TvSeriesKeywords200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TvSeriesKeywords200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'results': !exists(json, 'results') ? undefined : json['results'],
    };
}

export function TvSeriesKeywords200ResponseToJSON(value?: TvSeriesKeywords200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'results': value.results,
    };
}

