/* tslint:disable */
/* eslint-disable */
/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { TvSeriesWatchProviders200ResponseResults } from './TvSeriesWatchProviders200ResponseResults';
import {
    TvSeriesWatchProviders200ResponseResultsFromJSON,
    TvSeriesWatchProviders200ResponseResultsFromJSONTyped,
    TvSeriesWatchProviders200ResponseResultsToJSON,
} from './TvSeriesWatchProviders200ResponseResults';

/**
 * 
 * @export
 * @interface TvSeriesWatchProviders200Response
 */
export interface TvSeriesWatchProviders200Response {
    /**
     * 
     * @type {any}
     * @memberof TvSeriesWatchProviders200Response
     */
    id?: any | null;
    /**
     * 
     * @type {TvSeriesWatchProviders200ResponseResults}
     * @memberof TvSeriesWatchProviders200Response
     */
    results?: TvSeriesWatchProviders200ResponseResults;
}

/**
 * Check if a given object implements the TvSeriesWatchProviders200Response interface.
 */
export function instanceOfTvSeriesWatchProviders200Response(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function TvSeriesWatchProviders200ResponseFromJSON(json: any): TvSeriesWatchProviders200Response {
    return TvSeriesWatchProviders200ResponseFromJSONTyped(json, false);
}

export function TvSeriesWatchProviders200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TvSeriesWatchProviders200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'results': !exists(json, 'results') ? undefined : TvSeriesWatchProviders200ResponseResultsFromJSON(json['results']),
    };
}

export function TvSeriesWatchProviders200ResponseToJSON(value?: TvSeriesWatchProviders200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'results': TvSeriesWatchProviders200ResponseResultsToJSON(value.results),
    };
}

