/* tslint:disable */
/* eslint-disable */
/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TvSeasonWatchProviders200ResponseResultsAT
 */
export interface TvSeasonWatchProviders200ResponseResultsAT {
    /**
     * 
     * @type {any}
     * @memberof TvSeasonWatchProviders200ResponseResultsAT
     */
    link?: any | null;
    /**
     * 
     * @type {any}
     * @memberof TvSeasonWatchProviders200ResponseResultsAT
     */
    flatrate?: any | null;
    /**
     * 
     * @type {any}
     * @memberof TvSeasonWatchProviders200ResponseResultsAT
     */
    buy?: any | null;
}

/**
 * Check if a given object implements the TvSeasonWatchProviders200ResponseResultsAT interface.
 */
export function instanceOfTvSeasonWatchProviders200ResponseResultsAT(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function TvSeasonWatchProviders200ResponseResultsATFromJSON(json: any): TvSeasonWatchProviders200ResponseResultsAT {
    return TvSeasonWatchProviders200ResponseResultsATFromJSONTyped(json, false);
}

export function TvSeasonWatchProviders200ResponseResultsATFromJSONTyped(json: any, ignoreDiscriminator: boolean): TvSeasonWatchProviders200ResponseResultsAT {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'link': !exists(json, 'link') ? undefined : json['link'],
        'flatrate': !exists(json, 'flatrate') ? undefined : json['flatrate'],
        'buy': !exists(json, 'buy') ? undefined : json['buy'],
    };
}

export function TvSeasonWatchProviders200ResponseResultsATToJSON(value?: TvSeasonWatchProviders200ResponseResultsAT | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'link': value.link,
        'flatrate': value.flatrate,
        'buy': value.buy,
    };
}

