/* tslint:disable */
/* eslint-disable */
/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TvSeriesEpisodeGroups200Response
 */
export interface TvSeriesEpisodeGroups200Response {
    /**
     * 
     * @type {any}
     * @memberof TvSeriesEpisodeGroups200Response
     */
    results?: any | null;
    /**
     * 
     * @type {any}
     * @memberof TvSeriesEpisodeGroups200Response
     */
    id?: any | null;
}

/**
 * Check if a given object implements the TvSeriesEpisodeGroups200Response interface.
 */
export function instanceOfTvSeriesEpisodeGroups200Response(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function TvSeriesEpisodeGroups200ResponseFromJSON(json: any): TvSeriesEpisodeGroups200Response {
    return TvSeriesEpisodeGroups200ResponseFromJSONTyped(json, false);
}

export function TvSeriesEpisodeGroups200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TvSeriesEpisodeGroups200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'results': !exists(json, 'results') ? undefined : json['results'],
        'id': !exists(json, 'id') ? undefined : json['id'],
    };
}

export function TvSeriesEpisodeGroups200ResponseToJSON(value?: TvSeriesEpisodeGroups200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'results': value.results,
        'id': value.id,
    };
}

