/* tslint:disable */
/* eslint-disable */
/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TvSeriesWatchProviders200ResponseResultsRU
 */
export interface TvSeriesWatchProviders200ResponseResultsRU {
    /**
     * 
     * @type {any}
     * @memberof TvSeriesWatchProviders200ResponseResultsRU
     */
    link?: any | null;
    /**
     * 
     * @type {any}
     * @memberof TvSeriesWatchProviders200ResponseResultsRU
     */
    flatrate?: any | null;
    /**
     * 
     * @type {any}
     * @memberof TvSeriesWatchProviders200ResponseResultsRU
     */
    ads?: any | null;
}

/**
 * Check if a given object implements the TvSeriesWatchProviders200ResponseResultsRU interface.
 */
export function instanceOfTvSeriesWatchProviders200ResponseResultsRU(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function TvSeriesWatchProviders200ResponseResultsRUFromJSON(json: any): TvSeriesWatchProviders200ResponseResultsRU {
    return TvSeriesWatchProviders200ResponseResultsRUFromJSONTyped(json, false);
}

export function TvSeriesWatchProviders200ResponseResultsRUFromJSONTyped(json: any, ignoreDiscriminator: boolean): TvSeriesWatchProviders200ResponseResultsRU {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'link': !exists(json, 'link') ? undefined : json['link'],
        'flatrate': !exists(json, 'flatrate') ? undefined : json['flatrate'],
        'ads': !exists(json, 'ads') ? undefined : json['ads'],
    };
}

export function TvSeriesWatchProviders200ResponseResultsRUToJSON(value?: TvSeriesWatchProviders200ResponseResultsRU | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'link': value.link,
        'flatrate': value.flatrate,
        'ads': value.ads,
    };
}

